### ISSUE TITLE
streaming.py - line 313 - buf.read_line().strip - fails.

### ISSUE THREAD

**Issue by rokn1500** [tweepy/tweepy#1003]
intermittent bug, but occurs fairly frequently. twitter is sending something that cannot be handled as a string and the exception handling does not catch it. 
this is in tweepy 3.5 and i'm using python 3.6.

Traceback (most recent call last):
  File "newt5.py", line 223, in <module>
    sapi.filter(track=['BTC', 'Bitcoin'], languages = ['en'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tweepy/streaming.py", line 445, in filter
    self._start(async)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tweepy/streaming.py", line 294, in _run
    raise exception
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tweepy/streaming.py", line 263, in _run
    self._read_loop(resp)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tweepy/streaming.py", line 313, in _read_loop
    line = buf.read_line().strip()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by Harmon758** [comment]
This should be fixed by https://github.com/tweepy/tweepy/commit/32fa592d4ae535baf6e1cf17658d207fb656b16b (#1027) in 3.7.0.
For more information, see #1026.
