### ISSUE TITLE
get_authorization_url returns https max retries exceeded error

### ISSUE THREAD

**Issue by terencechow** [tweepy/tweepy#1041]
Trying to setup signing with twitter on my website and to store the users access token / secret after they've signed up. However seems like I am having a problem with even getting the request_token.

My code:
```
import tweepy
CONSUMER_KEY='...'
CONSUMER_SECRET='...'
auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
redirect_url = auth.get_authorization_url()  # <-- FAILS HERE
```

Error message
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/terence/.pyenv/versions/myapp/lib/python2.7/site-packages/tweepy/auth.py", line 88, in get_authorization_url
    raise TweepError(e)
TweepError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /oauth/request_token (Caused by SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:661)'),))
```

This isn't really making sense to me because I'm pretty much copying line for line the guide at the official site:

http://docs.tweepy.org/en/v3.6.0/auth_tutorial.html?highlight=get_access_token

Any suggestions?

**Comment by terencechow** [comment]
Closing.. this seems to work now? I have no idea what changed...

**Comment by terencechow** [comment]
Looks like the error is intermittent. It appears to be caused by an outdated openssl, see this github [issue](https://github.com/osfclient/osfclient/issues/74) on it.

Note that I have libressl so i'm not sure if thats whats causing it...
