### ISSUE TITLE
Asynchronous Streaming Errors Can't be Handled Externally

### ISSUE THREAD

**Issue by yblank1** [tweepy/tweepy#1072]
While streaming tweets, exceptions are thrown as appropriate. However, when the asynchronous streaming option is used, there doesn't seem to be a way to handle any exceptions as they occur in the new thread and are not passed back to the parent thread. Any attempt to override on_exception does not work either, as the exception is reraised regardless of how it is handled in the overridden function. 

This is the error that occurs for me: 

	Exception in thread Thread-1: 
	Traceback (most recent call last): 
	  File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 285, in recv_into 
	    return self.connection.recv_into(*args, **kwargs) 
	  File "/app/.heroku/python/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1814, in recv_into 
	    self._raise_ssl_error(self._ssl, result) 
	  File "/app/.heroku/python/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1614, in _raise_ssl_error 
	    raise WantReadError() 
	OpenSSL.SSL.WantReadError 
	During handling of the above exception, another exception occurred: 
	Traceback (most recent call last): 
	  File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 285, in recv_into 
	    return self.connection.recv_into(*args, **kwargs) 
	  File "/app/.heroku/python/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1814, in recv_into 
	    self._raise_ssl_error(self._ssl, result) 
	  File "/app/.heroku/python/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1631, in _raise_ssl_error 
	    raise SysCallError(errno, errorcode.get(errno)) 
	OpenSSL.SSL.SysCallError: (104, 'ECONNRESET') 
	During handling of the above exception, another exception occurred: 
	Traceback (most recent call last): 
	  File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/response.py", line 331, in _error_catcher 
	    yield 
	  File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/response.py", line 413, in read 
	    data = self._fp.read(amt) 
	  File "/app/.heroku/python/lib/python3.6/http/client.py", line 449, in read 
	    n = self.readinto(b) 
	  File "/app/.heroku/python/lib/python3.6/http/client.py", line 483, in readinto 
	    return self._readinto_chunked(b) 
	  File "/app/.heroku/python/lib/python3.6/http/client.py", line 578, in _readinto_chunked 
	    chunk_left = self._get_chunk_left() 
	  File "/app/.heroku/python/lib/python3.6/http/client.py", line 546, in _get_chunk_left 
	    chunk_left = self._read_next_chunk_size() 
	  File "/app/.heroku/python/lib/python3.6/http/client.py", line 506, in _read_next_chunk_size 
	    line = self.fp.readline(_MAXLINE + 1) 
	  File "/app/.heroku/python/lib/python3.6/socket.py", line 586, in readinto 
	    return self._sock.recv_into(b) 
	  File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 300, in recv_into 
	    return self.recv_into(*args, **kwargs) 
	  File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 290, in recv_into 
	    raise SocketError(str(e)) 
	OSError: (104, 'ECONNRESET') 
	During handling of the above exception, another exception occurred: 
	Traceback (most recent call last): 
	  File "/app/.heroku/python/lib/python3.6/threading.py", line 916, in _bootstrap_inner 
	    self.run() 
	  File "/app/.heroku/python/lib/python3.6/threading.py", line 864, in run 
	    self._target(*self._args, **self._kwargs) 
	  File "/app/.heroku/python/lib/python3.6/site-packages/tweepy/streaming.py", line 297, in _run 
	    six.reraise(*exc_info) 
	  File "/app/.heroku/python/lib/python3.6/site-packages/six.py", line 693, in reraise 
	    raise value 
	  File "/app/.heroku/python/lib/python3.6/site-packages/tweepy/streaming.py", line 266, in _run 
	    self._read_loop(resp) 
	  File "/app/.heroku/python/lib/python3.6/site-packages/tweepy/streaming.py", line 316, in _read_loop 
	    line = buf.read_line().strip() 
	  File "/app/.heroku/python/lib/python3.6/site-packages/tweepy/streaming.py", line 181, in read_line 
	    self._buffer += self._stream.read(self._chunk_size) 
	  File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/response.py", line 430, in read 
	    raise IncompleteRead(self._fp_bytes_read, self.length_remaining) 
	  File "/app/.heroku/python/lib/python3.6/contextlib.py", line 99, in __exit__ 
	    self.gen.throw(type, value, traceback) 
	  File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/response.py", line 349, in _error_catcher 
	    raise ProtocolError('Connection broken: %r' % e, e) 
	urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(104, \'ECONNRESET\')",)', OSError("(104, 'ECONNRESET')",))

**Comment by gnullByte** [comment]
Did you happen to make any progress on this? I'm also curious about this. I can't seem to handle `urllib3.exceptions.ProtocolError` or `urllib3.exceptions.ReadTimeoutError` from my main thread.

**Comment by thelazyliz** [comment]
you can't handle from main thread. what worked for me was to exit the streaming thread on exception, and have another watcher thread to watch if the stream is still running, and if it is not running, start a new streaming thread. it's a bit hacky but it works.

**Comment by Harmon758** [comment]
For `urllib3.exceptions.ProtocolError` and `urllib3.exceptions.ReadTimeoutError` specifically, they should now be handled by Tweepy itself, with https://github.com/tweepy/tweepy/commit/68e19cc6b9b23d72369ca1520093770eb18a5a9f.
