### ISSUE TITLE
Cannot advance cursor to next page (code 403)

### ISSUE THREAD

**Issue by ClemSc** [tweepy/tweepy#1137]
Hello !
This might be a twitter related issue instead of tweepy. If I make a cursor on tweepy.API.search, then I cannot proceed to the next page (cursor.next() is answered a code 403). First page is recovered.
I have tried to time.sleep between each page iteration (up to 15 minutes per page, which seems a be extreme to recover 100 status), that does not help. If I select items instead of pages, the same problem occurs at the end of page 1. Any idea to overcome this ?

Tweepy is version 3.7.0
My code:
```python
import tweepy
from tweepy import OAuthHandler, Stream, API, Cursor
import time

auth = tweepy.OAuthHandler('XXX', 'XXX')
auth.set_access_token('XXX', 'XXX')
api = tweepy.API(auth)
q = "valid query below 500 char"
count = 0
res = list()
cursor = Cursor(api.search,
                    q=q,
                    lang="fr",
                    tweet_mode='extended',
                    count=100).pages()
for page in cursor:
    count +=1
    print("page:",count)
    res.append(page)
    print("sleep for 100 sec")
    time.sleep(100)
    print("continue")
```
```bash
Traceback (most recent call last):
  File "search_tweet.py", line 65, in <module>
    for page in cursor:
  File "/home/clement/.virtualenvs/mypy/lib/python3.6/site-packages/tweepy/cursor.py", line 49, in __next__
    return self.next()
  File "/home/clement/.virtualenvs/mypy/lib/python3.6/site-packages/tweepy/cursor.py", line 108, in next
    data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kargs)
  File "/home/clement/.virtualenvs/mypy/lib/python3.6/site-packages/tweepy/binder.py", line 250, in _call
    return method.execute()
  File "/home/clement/.virtualenvs/mypy/lib/python3.6/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Twitter error response: status code = 403
```

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
What's the response text for the error?

**Comment by hmoazam** [comment]
Adding a small explanation as I encountered the same issue, and this may help others understand what's going as well. 

The Twitter documentation states the query length limit to be 512 characters (for essential and elevated access levels). However, tweepy builds the query for us internally. I believe when we iterate over pages with the tweepy cursor, it is adding a parameter to specify the page number (after the first page) which results in the behaviour reported by @ClemSc, i.e. erroring out after the first page.
