### ISSUE TITLE
JSONDecodeError when trying to parse tweets from stream object.

### ISSUE THREAD

**Issue by stramzik** [tweepy/tweepy#1204]
Hi,
I am trying to stream tweets in particular language and parse from the JSON string object.
But I think the some of the tweets are not json string objects when I try to stream,(I MAYBE COMPLETELY WRONG)

Below is the code which I am using ** FYI I does stream tweets and after few tweets I get the error mentioned below after code,

```
from tweepy import API
from tweepy import Cursor
from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream
from textblob import TextBlob
from googletrans import Translator
import json
import re

ACCESS_TOKEN = "2446723783-cqGTmWPdtJI5HhCT7UmmET2xVY7xlA1RqlBQdQl"
ACCESS_TOKEN_SECRET = "6ZRIqd9HDCgZxsR6iMUbt6eOgk1YVsz59lEsvL30eFnPf"
CONSUMER_KEY = "slWhR4Z6VOjp0R3ojx1B2a4pr"
CONSUMER_SECRET = "6OrySqqUIwQM8ioBycqbStWizM6KkLCMFecjXPvbVmsrsw6eNT"

Count = 0


translator = Translator()
class StdOutListener(StreamListener):
    
    def on_data(self, data):
        global Count
        #Data has the JSON STring
        y = json.loads(data)  #Data is a JSON string converting to JSON object to call
        print("--------------------")
        try:
            y = y['extended_tweet']['full_text']
            y = str(y)
            translations = translator.translate(y, src='pt', dest='en')
            print(translations.origin, '\n -> \n', translations.text)
            z = translations.text

            Count = Count + 1
            print(Count)
        except KeyError:
            y = y['text']
            y = str(y)
            translations = translator.translate(y, src='pt', dest='en')
            print(translations.origin, '\n -> \n', translations.text)
            z = translations.text

            Count = Count + 1
            print(Count)

        analysis = TextBlob(z)

        if analysis.sentiment.polarity > 0:
            print("sentiment is positiv")
        elif analysis.sentiment.polarity == 0:
            print("sentiment is Neutral")
        else:
            print("sentiment is Negative")
        print("--------------------\n")    
            
        return True

    def on_error(self,status):
        print(status)


if __name__ == "__main__":
    listener=StdOutListener()
    auth = OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
    auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)

    stream = Stream(auth, listener)
    stream.filter(track=['como'],languages=['pt'])
       
```
The Trackback is as below
```
--------------------
RT @Low__easy: Tirar Paulo Freire,
de qualquer lugar imaginário
é um feito imbatível e insuperável,
com repercussão na eternidade,
pelo séc… 
 -> 
 RT @Low__easy: Take Paulo Freire,
from any imaginary place
is an unbeatable and unsurpassed feat,
with repercussion in eternity,
by the ...
1
sentiment is Neutral
--------------------

--------------------
RT @Du_carvalho21: Como as coisas mudam ahaha 
 -> 
 RT @Danielle: How do you change ahaha?
2
sentiment is Neutral
--------------------

--------------------
Traceback (most recent call last):
  File "C:\Users\ManoharRaoN\Desktop\SentizAnalyzer\siraj.py", line 68, in <module>
    stream.filter(track=['como'],languages=['pt'])
  File "C:\Users\ManoharRaoN\AppData\Local\Programs\Python\Python37\lib\site-packages\tweepy\streaming.py", line 453, in filter
    self._start(is_async)
  File "C:\Users\ManoharRaoN\AppData\Local\Programs\Python\Python37\lib\site-packages\tweepy\streaming.py", line 368, in _start
    self._run()
  File "C:\Users\ManoharRaoN\AppData\Local\Programs\Python\Python37\lib\site-packages\tweepy\streaming.py", line 300, in _run
    six.reraise(*exc_info)
  File "C:\Users\ManoharRaoN\AppData\Local\Programs\Python\Python37\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\ManoharRaoN\AppData\Local\Programs\Python\Python37\lib\site-packages\tweepy\streaming.py", line 269, in _run
    self._read_loop(resp)
  File "C:\Users\ManoharRaoN\AppData\Local\Programs\Python\Python37\lib\site-packages\tweepy\streaming.py", line 331, in _read_loop
    self._data(next_status_obj)
  File "C:\Users\ManoharRaoN\AppData\Local\Programs\Python\Python37\lib\site-packages\tweepy\streaming.py", line 303, in _data
    if self.listener.on_data(data) is False:
  File "C:\Users\ManoharRaoN\Desktop\SentizAnalyzer\siraj.py", line 39, in on_data
    translations = translator.translate(y, src='pt', dest='en')
  File "C:\Users\ManoharRaoN\AppData\Local\Programs\Python\Python37\lib\site-packages\googletrans\client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "C:\Users\ManoharRaoN\AppData\Local\Programs\Python\Python37\lib\site-packages\googletrans\client.py", line 81, in _translate
    data = utils.format_json(r.text)
  File "C:\Users\ManoharRaoN\AppData\Local\Programs\Python\Python37\lib\site-packages\googletrans\utils.py", line 62, in format_json
    converted = legacy_format_json(original)
  File "C:\Users\ManoharRaoN\AppData\Local\Programs\Python\Python37\lib\site-packages\googletrans\utils.py", line 54, in legacy_format_json
    converted = json.loads(text)
  File "C:\Users\ManoharRaoN\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ManoharRaoN\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ManoharRaoN\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[Finished in 6.3s with exit code 1]
[shell_cmd: python -u "C:\Users\ManoharRaoN\Desktop\SentizAnalyzer\siraj.py"]
[dir: C:\Users\ManoharRaoN\Desktop\SentizAnalyzer]
[path: C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Webex\Webex\Applications;C:\Program Files\IBM\SPSS\Modeler\18.1.1\ext\bin\spss.TMWBServer\bin;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Users\ManoharRaoN\AppData\Local\Programs\Python\Python37;C:\Users\ManoharRaoN\AppData\Local\Programs\Python\Python37\Scripts;C:\Users\ManoharRaoN\AppData\Roaming\nltk_data;C:\Users\ManoharRaoN\AppData\Local\Microsoft\WindowsApps;C:\Users\ManoharRaoN\AppData\Local\Box\Box Edit\]
```
Please let me know how I can fix this. I tried to encode but even that doesnt work

**Comment by machine-uprising** [comment]
@stramzik if the API keys in the code you provided are your actual API keys you need to generate new keys.

The error looks like a problem caused by googletranslate and not a problem with tweepy.

This SO post (https://stackoverflow.com/questions/49497391/googletrans-api-error-expecting-value-line-1-column-1-char-0) shows that the problem might be rate limiting. Another person on the post said the problem was caused by an emoji in the string being translated.

**Comment by Harmon758** [comment]
As mentioned, you're going to want to revoke and regenerate your keys and tokens now.

As also mentioned, this seems to be an issue with [googletrans](https://github.com/ssut/py-googletrans) rather than Tweepy.
See https://github.com/ssut/py-googletrans/issues/47, https://github.com/ssut/py-googletrans/issues/49, and https://github.com/ssut/py-googletrans/issues/106.

Feel free to create a new issue if you're able to print the data in question and confirm that it's not valid JSON.
