### ISSUE TITLE
Failed to send request

### ISSUE THREAD

**Issue by Gjpvernant** [tweepy/tweepy#1268]
I have written two years ago a code which perfectly worked, which is runned from time to time to handle a Twitter account. Running it now, I get this error message that I do not understand:

Traceback (most recent call last):
  File "API_Volante.py", line 18, in <module>
    user = api.get_user('@gjpvernant')
  File "/Users/admin/GJPVAPI/tweepy/binder.py", line 250, in _call
    return method.execute()
  File "/Users/admin/GJPVAPI/tweepy/binder.py", line 192, in execute
    six.reraise(TweepError, TweepError('Failed to send request: %s' % e), sys.exc_info()[2])
  File "/Users/admin/GJPVAPI/tweepy/binder.py", line 190, in execute
    proxies=self.api.proxy)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
tweepy.error.TweepError: Failed to send request: ('Connection aborted.', error(54, 'Connection reset by peer'))

Any idea what could go wrong?

**Comment by Harmon758** [comment]
This is simply an issue connecting to Twitter's API.
The error is telling you that Twitter's API has aborted/terminated the connection.
