### ISSUE TITLE
media_ids=[] gives Ssl.error

### ISSUE THREAD

**Issue by marcusl** [tweepy/tweepy#1288]
Calling `api.update_status(tweet['text'], media_ids=[])` gives the following traceback(s), but `None` works as expected. This is for 3.8.0:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 444, in wrap_socket
    cnx.do_handshake()
  File "/home/macke/.local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/macke/.local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/home/macke/.local/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_record', 'wrong version number')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 463, in send
    low_conn.endheaders()
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/usr/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 450, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/macke/.local/lib/python3.6/site-packages/tweepy/binder.py", line 189, in execute
    proxies=self.api.proxy)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/macke/fridaybot/fridaybot.py", line 75, in <module>
    send_friday_yaml_tweet()
  File "/home/macke/fridaybot/fridaybot.py", line 67, in send_friday_yaml_tweet
    api.update_status(tweet['text'], media_ids=media_ids, attachment_url=tweet.get('video'))
  File "/home/macke/.local/lib/python3.6/site-packages/tweepy/api.py", line 193, in update_status
    )(post_data=post_data, *args, **kwargs)
  File "/home/macke/.local/lib/python3.6/site-packages/tweepy/binder.py", line 250, in _call
    return method.execute()
  File "/home/macke/.local/lib/python3.6/site-packages/tweepy/binder.py", line 191, in execute
    six.reraise(TweepError, TweepError('Failed to send request: %s' % e), sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/macke/.local/lib/python3.6/site-packages/tweepy/binder.py", line 189, in execute
    proxies=self.api.proxy)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
tweepy.error.TweepError: Failed to send request: ("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)",)

```

**Comment by Harmon758** [comment]
I'm unable to reproduce this. It also doesn't make much sense, as `list_to_csv` should be converting the empty list to `None` anyways. I'm also not sure how the error/traceback is related.
Are you able to provide a reproducible example (MCVE/SSCCE)?
