### ISSUE TITLE
UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by veganbread** [tweepy/tweepy#1409]
Not sure if that's an issue, this error occurs after the script runs for +- 5 min.

```python
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\godly-project\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\godly-project\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\godly-project\lib\site-packages\tweepy\streaming.py", line 320, in _run
    six.reraise(*exc_info)
  File "C:\ProgramData\Anaconda3\envs\godly-project\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\envs\godly-project\lib\site-packages\tweepy\streaming.py", line 289, in _run
    self._read_loop(resp)
  File "C:\ProgramData\Anaconda3\envs\godly-project\lib\site-packages\tweepy\streaming.py", line 349, in _read_loop
    next_status_obj = buf.read_len(length)
  File "C:\ProgramData\Anaconda3\envs\godly-project\lib\site-packages\tweepy\streaming.py", line 183, in read_len
    self._buffer += self._stream.read(read_len)
  File "C:\ProgramData\Anaconda3\envs\godly-project\lib\site-packages\urllib3\response.py", line 546, in read
    if data:
UnboundLocalError: local variable 'data' referenced before assignment
```

Im running on the newest version 3.1.0 using -> `from tweepy.streaming import StreamListener`

**Comment by Harmon758** [comment]
[Tweepy v3.1.0](https://github.com/tweepy/tweepy/releases/tag/v3.1.0) is over 5 years old now. The latest version of Tweepy is v3.9.0.
Regardless, this seems to be an issue with urllib3 rather than Tweepy.
You don't seem to be using the latest version of urllib3 either though, since [the line that errors is on line 542 in urllib3 v1.25.10](https://github.com/urllib3/urllib3/blob/1.25.10/src/urllib3/response.py#L542).
Feel free to provide an updated traceback if you're still able to reproduce this with the latest updated versions of both libraries, but this is unlikely to be an issue with Tweepy.
