### ISSUE TITLE
Over capacity

### ISSUE THREAD

**Issue by nrmv** [tweepy/tweepy#1558]
Code:
```
import tweepy

consumer_key = ""
consumer_secret = ""
access_token = ""
access_token_secret =""

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True, compression=True)

ids = []

for page in tweepy.Cursor(api.followers_ids, screen_name="TicTocTick").pages():
    ids.extend(page)
```

Error:
```
Traceback (most recent call last):
  File "C:\Users\Andrey\Desktop\twitter_brook\program.py", line 17, in <module>
    for page in tweepy.Cursor(api.followers_ids, screen_name="TicTocTick").pages():
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\cursor.py", line 51, in __next__
    return self.next()
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\cursor.py", line 75, in next
    data, cursors = self.method(cursor=self.next_cursor,
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\Andrey\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'message': 'Over capacity', 'code': 130}]

```

**Comment by Harmon758** [comment]
This is an error response from Twitter's API, with 130 and "Over capacity" referring to Twitter / the API itself being temporarily over capacity, rather than an issue with Tweepy.
See https://developer.twitter.com/en/support/twitter-api/error-troubleshooting#error-codes.

**Comment by nrmv** [comment]
How to solve this problem?

**Comment by Harmon758** [comment]
Again, it's an issue on Twitter's end. There's nothing to do but wait until it's no longer over capacity.
