### ISSUE TITLE
ConnectionResetError with followers_list endpoint

### ISSUE THREAD

**Issue by MoroccanGeek** [tweepy/tweepy#1583]
Hello, so I'm trying to use the followers_list endpoint, and today I faced the error below. I am sure that there's no other connection than the one I'm trying to make, and I'm sure that the endpoint rate limits are 15 for OAuth1 and 30 for OAuth 2 (i'm using rate_limit_status by Twitter API to get the endpoints remaining requests):

My scripts were always working and I have never faced this issue until today.

P.S: I'm using Tweepy 3.9.0 and Python 3.9.0

`Traceback (most recent call last):
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\urllib3\response.py", line 436, in _error_catcher
    yield
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\urllib3\response.py", line 518, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\saber\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 458, in read    
    n = self.readinto(b)
  File "C:\Users\saber\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\saber\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto     
    return self._sock.recv_into(b)
  File "C:\Users\saber\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1241, in recv_into      
    return self.read(nbytes, buffer)
  File "C:\Users\saber\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\requests\models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\urllib3\response.py", line 575, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\urllib3\response.py", line 540, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\saber\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\urllib3\response.py", line 454, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly 
closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\tweepy\binder.py", line 184, in execute
    resp = self.session.request(self.method,
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\requests\sessions.py", line 685, in send
    r.content
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\requests\models.py", line 829, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\requests\models.py", line 754, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\saber\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main        
    return _run_code(code, main_globals, None,
  File "C:\Users\saber\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\saber\.vscode\extensions\ms-python.python-2021.5.829140558\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\saber\.vscode\extensions\ms-python.python-2021.5.829140558\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\saber\.vscode\extensions\ms-python.python-2021.5.829140558\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\saber\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\saber\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\saber\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\tweepy\binder.py", line 252, in _call
    return method.execute()
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\tweepy\binder.py", line 192, in execute
    six.reraise(TweepError, TweepError('Failed to send request: %s' % e), sys.exc_info()[2])
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\tweepy\binder.py", line 184, in execute
    resp = self.session.request(self.method,
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\requests\sessions.py", line 685, in send
    r.content
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\requests\models.py", line 829, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "c:\Users\saber\Desktop\myenv\lib\site-packages\requests\models.py", line 754, in generate
    raise ChunkedEncodingError(e)
tweepy.error.TweepError: Failed to send request: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the 
remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))`

**Comment by Harmon758** [comment]
Closing this in favor of #1606
