### ISSUE TITLE
Error while trying to initialize a custom StreamListener

### ISSUE THREAD

**Issue by Technerder** [tweepy/tweepy#1602]
I'm trying to use tweepy to stream tweets but I'm running into the following error.

```py
import tweepy
import dataset


class TwitterStreamer(tweepy.StreamListener):

    def __init__(self, db):
        self.db = db

    def on_status(self, status):
        print(f'@{status.author.screen_name:<16} -> {status.text}')


if __name__ == '__main__':
    db = dataset.connect('sqlite:///database.db')
    auth = tweepy.OAuthHandler('', '')
    auth.set_access_token('', '')
    tweepy.Stream(tweepy.API(auth).auth, TwitterStreamer(db)).filter(track=['test_topic'])
```

```error
Traceback (most recent call last):
  File "C:/Users/Technerder/Dev/Playground/twitter_streamer.py", line 18, in <module>
    tweepy.Stream(tweepy.API(auth).auth, TwitterStreamer(db)).filter(track=['test_topic'])
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\streaming.py", line 474, in filter
    self._start(is_async)
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\streaming.py", line 389, in _start
    self._run()
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\streaming.py", line 320, in _run
    six.reraise(*exc_info)
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\streaming.py", line 289, in _run
    self._read_loop(resp)
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\streaming.py", line 351, in _read_loop
    self._data(next_status_obj)
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\streaming.py", line 323, in _data
    if self.listener.on_data(data) is False:
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\streaming.py", line 53, in on_data
    status = Status.parse(self.api, data)
AttributeError: 'TwitterStreamer' object has no attribute 'api'
```

What am I doing wrong?

**Comment by generousjj** [comment]
Per https://stackoverflow.com/questions/50652687/attributeerror-mystreamlistener-object-has-no-attribute-api-tweepy-error :

Adding `super(MyStreamListener, self).__init__()` at the beginning of `__init__` fixes it
``
def __init__(self):
    super(MyStreamListener, self).__init__()
    #initializes the counter
    self.counter = 0 
``

**Comment by Technerder** [comment]
Thanks, I just remembered that I needed to call super at the start of ``__init__``.
