### ISSUE TITLE
How to check the if twitter handle is deleted?

### ISSUE THREAD

**Issue by Gautamshahi** [tweepy/tweepy#1644]
I want to check if some Twitter handle is deleted or suspended. I tried to find some way, but I am not able to check it.

Is there any URL or standard lookup service from Twitter to check the account status?

**Comment by Harmon758** [comment]
You can use the [GET users/show](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-users-show) Twitter API endpoint with [`API.get_user`](https://tweepy.readthedocs.io/en/v3.10.0/api.html#API.get_user):
```pycon
>>> api.get_user(screen_name='b')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Program Files\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 63, 'message': 'User has been suspended.'}]
```
```pycon
>>> api.get_user(screen_name='m')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Program Files\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 50, 'message': 'User not found.'}]
```
You can handle the `TweepError` and check its `api_code` attribute to determine whether the account is suspended or not found, with 50 corresponding with not found and 63 with suspended. See https://developer.twitter.com/en/support/twitter-api/error-troubleshooting.

Note, however, that there is no distinction between a deleted account and one that never existed.
