### ISSUE TITLE
SyntaxError: invalid syntax|self, auth=None, *, cache=None, host='api.twitter.com', parser=None,

### ISSUE THREAD

**Issue by arjunAryaGit** [tweepy/tweepy#1723]
Traceback (most recent call last):
  File "temp.py", line 1, in <module>
    import tweepy
  File "/usr/lib/python2.7/site-packages/tweepy/__init__.py", line 12, in <module>
    from tweepy.api import API
  File "/usr/lib/python2.7/site-packages/tweepy/api.py", line 93
    self, auth=None, *, cache=None, host='api.twitter.com', parser=None,
                      ^
SyntaxError: invalid syntax

**Comment by Harmon758** [comment]
Support for Python 2 was dropped with v4.0.0.
See #1253.
