### ISSUE TITLE
Possible Request Error bug Report

### ISSUE THREAD

**Issue by lidd77** [tweepy/tweepy#1732]
Hey,  

I use tweepy.Curosr() for pages() function,  I got the next error : 
```

Traceback (most recent call last):
  File "/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    self._dns_host = value
  File "/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    # Using the value from allowed_gai_family() in the context of getaddrinfo lets
  File "python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

```

what casued this error ？  its Request package bug ??

Expecting your reply ! 

Thanks .

**Comment by Harmon758** [comment]
This is a network-level (possibly DNS) error.
Make sure you're able to connect to Twitter.
