### ISSUE TITLE
streaming.py crash

### ISSUE THREAD

**Issue by scardig** [tweepy/tweepy#18]
Downloaded streamwatcher.py from tweepy-examples. Sometimes, after a day of running, it crashes with the following (I commented out lines 117->119 in stremaing.py to catch the exception):

Traceback (most recent call last):
  File "webapps/siti/mex/scripts/mystreamwatcher.py", line 68, in <module>
    myfunc()
  File "webapps/siti/mex/scripts/mystreamwatcher.py", line 63, in myfunc
    stream.filter(followed)
  File "/home/user/webapps/siti/mex/scripts/tweepy/streaming.py", line 195, in filter
    self._start(async)
  File "/home/user/webapps/siti/mex/scripts/tweepy/streaming.py", line 160, in _start
    self._run()
  File "/home/user/webapps/siti/mex/scripts/tweepy/streaming.py", line 111, in _run
    self._read_loop(resp)
  File "/home/user/webapps/siti/mex/scripts/tweepy/streaming.py", line 140, in _read_loop
    c = resp.read(1)
  File "/usr/local/lib/python2.6/httplib.py", line 517, in read
    return self._read_chunked(amt)
  File "/usr/local/lib/python2.6/httplib.py", line 563, in _read_chunked
    raise IncompleteRead(value)
httplib.IncompleteRead

**Comment by Harmon758** [comment]
This seems to have been fixed with https://github.com/tweepy/tweepy/commit/fae9091486bd5e1f7bc7ee0bf7c30651b2086462 (#498), but was reverted with https://github.com/tweepy/tweepy/commit/34af675c8e24b5176dae276342126fb52816ae6e, due to https://github.com/tweepy/tweepy/issues/501. See #237.
