### ISSUE TITLE
403 encounter error

### ISSUE THREAD

**Issue by elon2022** [tweepy/tweepy#1879]
I applied for the advanced permission of the twitter API, and then used API 1.1 for development. I found that I failed to run, and the administrator asked me to use API2. Did I use it or report an error?

**Comment by elon2022** [comment]
import tweepy
import config
import requests
client =tweepy.Client(bearer_token=config.Bearer_Token)

query='communi3 -is:retweet'
response=client.search_recent_tweets(query=query,max_results=10)
print(response)

**Comment by elon2022** [comment]
C:\Users\Administrator\Anaconda3\envs\twitter_bot\python.exe D:/twitter_bot/3.py
Traceback (most recent call last):
  File "D:/twitter_bot/3.py", line 7, in <module>
    response=client.search_recent_tweets(query=query,max_results=10)
  File "C:\Users\Administrator\Anaconda3\envs\twitter_bot\lib\site-packages\tweepy\client.py", line 1255, in search_recent_tweets
    ), data_type=Tweet, user_auth=user_auth
  File "C:\Users\Administrator\Anaconda3\envs\twitter_bot\lib\site-packages\tweepy\client.py", line 127, in _make_request
    json=json, user_auth=user_auth)
  File "C:\Users\Administrator\Anaconda3\envs\twitter_bot\lib\site-packages\tweepy\client.py", line 85, in request
    auth=auth
AttributeError: __enter__

**Comment by elon2022** [comment]
my tweepy version 4.8.0

**Comment by Harmon758** [comment]
Your traceback has no indication of a 403 error.
What versions of Python and requests are you using?

For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

**Comment by Anurag-Varma** [comment]
Have the same error, 403

While using filter
