### ISSUE TITLE
tweepy.errors.TweepyException: 'oauth_token'

### ISSUE THREAD

**Issue by fabge** [tweepy/tweepy#1952]
I am to authenticate via the 3-legged OAuth flow (tweepy 4.10.1).
After clicking through the authorization flow via the url obtained through `oauth1_user_handler.get_authorization_url(signin_with_twitter=True)` I do get a response with the following URL:

```
https://127.0.0.1:8000/twitter/authorize?oauth_token=PsaU5gAAAAABd5djasdfyw_8&oauth_verifier=L4zUUNS1pxYJQJQ3h2di4Fe3asdfXA
```

I am then parsing the `oauth_verifier` and pass it to Tweepy:

```python
access_token, access_token_secret = oauth_user_handler.get_access_token(oauth_verifier)
```

However then, Tweepy throws following error:
```bash
Traceback (most recent call last):
  File "/Users/fabian/.venv/venv/lib/python3.9/site-packages/tweepy/auth.py", line 91, in get_access_token
    resource_owner_key=self.request_token['oauth_token'],
KeyError: 'oauth_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fabian/.venv/venv/lib/python3.9/site-packages/django/contrib/staticfiles/handlers.py", line 80, in __call__
    return self.application(environ, start_response)
  File "/Users/fabian/.venv/venv/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 132, in __call__
    response = self.get_response(request)
  File "/Users/fabian/.venv/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/Users/fabian/.venv/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/Users/fabian/.venv/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 139, in response_for_exception
    response = handle_uncaught_exception(
  File "/Users/fabian/.venv/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 180, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/fabian/.venv/venv/lib/python3.9/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "/Users/fabian/.venv/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/fabian/.venv/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fabian/.venv/venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/fabian/code/rrread/app/rrread/views.py", line 290, in twitter_authorize
    access_token, access_token_secret = oauth_user_handler.get_access_token(oauth_verifier)
  File "/Users/fabian/.venv/venv/lib/python3.9/site-packages/tweepy/auth.py", line 101, in get_access_token
    raise TweepyException(e)
tweepy.errors.TweepyException: 'oauth_token'
```

I have found a [StackOverflow](https://stackoverflow.com/questions/73480284/how-do-i-verify-a-tweepy-api-using-3-legged-auth/73526989#73526989) post from 4 days ago with the exact problem.

I am not sure what the issue is. It seems `resp = self.oauth.fetch_access_token(url)` is not working correctly.

Any help is appreciated. Thanks!

**Comment by Harmon758** [comment]
If you're reinitializing `OAuth1UserHandler` and not using the same instance, you need to set the request token and secret before using the verifier to get the access token and secret.

There's a section on this in the documentation: https://tweepy.readthedocs.io/en/v4.10.1/authentication.html#legged-oauth

**Comment by fabge** [comment]
I'm sorry, you're right, this was my mistake. Reinitializing like described in the docs worked!
