### ISSUE TITLE
error with field edit_history_tweet_ids

### ISSUE THREAD

**Issue by liabozarth** [tweepy/tweepy#1994]
This appears to be an error with the Tweet.py file

`Stream encountered an exception
Traceback (most recent call last):
  File "/home/ciptools/data-loaders/covid19-api-v2/venv/lib/python3.9/site-packages/tweepy/streaming.py", line 92, in _connect
    self.on_data(line)
  File "/home/ciptools/data-loaders/covid19-api-v2/venv/lib/python3.9/site-packages/tweepy/streaming.py", line 926, in on_data
    includes = self._process_includes(data["includes"])
  File "/home/ciptools/data-loaders/covid19-api-v2/venv/lib/python3.9/site-packages/tweepy/client.py", line 164, in _process_includes
    includes["tweets"] = [Tweet(tweet) for tweet in includes["tweets"]]
  File "/home/ciptools/data-loaders/covid19-api-v2/venv/lib/python3.9/site-packages/tweepy/client.py", line 164, in <listcomp>
    includes["tweets"] = [Tweet(tweet) for tweet in includes["tweets"]]
  File "/home/ciptools/data-loaders/covid19-api-v2/venv/lib/python3.9/site-packages/tweepy/tweet.py", line 121, in __init__
    map(int, data["edit_history_tweet_ids"])
KeyError: 'edit_history_tweet_ids'
`

My code

`

    # This is where we set our filter rule
    streamer.add_rule()

    expansions =  "author_id,referenced_tweets.id,in_reply_to_user_id,geo.place_id,entities.mentions.username,referenced_tweets.id.author_id",
    user_fields =  "created_at,description,entities,id,location,name,protected,public_metrics,url,username,verified,withheld",
    tweet_fields= "attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,public_metrics,possibly_sensitive,referenced_tweets,source,text,withheld",
    place_fields= "contained_within,country,country_code,full_name,geo,id,name,place_type",

    #return hydrated tweet
    cs.filter(user_fields=user_fields, tweet_fields=tweet_fields, place_fields=place_fields, expansions=expansions)

`

**Comment by Harmon758** [comment]
This seems like it might be a bug with the Twitter API, since `edit_history_tweet_ids` should be a default Tweet field.

For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

**Comment by meiji163** [comment]
This is also breaking my existing code when I initialize a `tweepy.Tweet` from a dict

 ```python
import tweepy
tweepy.Tweet(data={"id":1, "text":"example"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/meiji163/miniconda3/lib/python3.8/site-packages/tweepy/tweet.py", line 128, in __init__
    map(int, data["edit_history_tweet_ids"])
KeyError: 'edit_history_tweet_ids'
 ```

**Comment by Harmon758** [comment]
While adding support for the edit metadata, it did occur to me that it might be a breaking change in terms of how `Tweet` is initialized. I supposed there are possible use cases for wanting to use old data to construct the model. For now, I've changed it to handle the `KeyError` and warn about it being missing instead, with https://github.com/tweepy/tweepy/commit/3dea0df2b8ee797264de67afc9f2d670e68aa634. This is a stopgap, but I don't really see another way to keep backwards-compatibility when the Twitter API adds new default fields to models.
