### ISSUE TITLE
Error while uploading GIFs: "File size exceeds 5242880 bytes", even tho the file is under Twitter's limits

### ISSUE THREAD

**Issue by jetley** [tweepy/tweepy#2002]
Hi,

I'm rewiriting and old bot of mine. The bot generates random content from a series of video files (as still image or GIF) and then uploads it to Twitter. 

When I try to upload a GIF, sometimes it gets uploaded, but sometimes not. When it happens, Tweepy throws the following error:  `File size exceeds 5242880 bytes.` , but the current file size is 5,84Mb wich is under Twitter's max file size limit ([Link](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices)), 15Mb.

By the way, Tweepy always throws the same error (`File size exceeds 5242880 bytes.`) regardless of the file size whenever it doesn't get uploaded.

Here's how I upload it:
```python
mediaUpload = api.media_upload(filename="./media_upload/GIF.gif", chunked=True)
api.update_status(data[5], media_ids=[mediaUpload.media_id_string])
```
The full error, just in case:
```
Traceback (most recent call last):
  File "e:\002 PROGRAMACIÓ\003 NoContextBot V2\main.py", line 55, in <module>
    mediaUpload = api.media_upload(filename="./media_upload/GIF.gif", chunked=True)
  File "C:\Users\34684\AppData\Local\Programs\Python\Python310\lib\site-packages\tweepy\api.py", line 3554, in media_upload
    return self.chunked_upload(
  File "C:\Users\34684\AppData\Local\Programs\Python\Python310\lib\site-packages\tweepy\api.py", line 3665, in chunked_upload
    media_id = self.chunked_upload_init(
  File "C:\Users\34684\AppData\Local\Programs\Python\Python310\lib\site-packages\tweepy\api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "C:\Users\34684\AppData\Local\Programs\Python\Python310\lib\site-packages\tweepy\api.py", line 3791, in chunked_upload_init
    return self.request(
  File "C:\Users\34684\AppData\Local\Programs\Python\Python310\lib\site-packages\tweepy\api.py", line 255, in request
    raise BadRequest(resp)
tweepy.errors.BadRequest: 400 Bad Request
File size exceeds 5242880 bytes.
```

Using Tweepy 4.12.0.

**Comment by Harmon758** [comment]
You need to pass the `media_category` parameter for [`API.media_upload`](https://tweepy.readthedocs.io/en/v4.12.0/api.html#tweepy.API.media_upload) as `"dm_gif"` or `"tweet_gif"`.
See also the Twitter API documentation that you linked.
