### ISSUE TITLE
Issues deleting a DM message "delete_direct_message" 

### ISSUE THREAD

**Issue by Wittline** [tweepy/tweepy#2051]
Hi There, 

I am facing this problem whenever I try to delete a DM using: self.__api.delete_direct_message(id = id).

I`m missing something?

--- Logging error ---
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\tweepy\parsers.py", line 37, in parse
    json = json_lib.loads(payload)
  File "C:\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pouchmentions.py", line 1039, in __check_dms
    self.mention_platform.delete_dm(id = id)
  File "pouchmentions.py", line 562, in delete_dm
    self.__api.delete_direct_message(id = id)
  File "C:\Python\Python37\lib\site-packages\tweepy\api.py", line 3183, in delete_direct_message
    ), id=id, **kwargs
  File "C:\Python\Python37\lib\site-packages\tweepy\api.py", line 273, in request
    payload_type=payload_type, return_cursors=return_cursors
  File "C:\Python\Python37\lib\site-packages\tweepy\parsers.py", line 39, in parse
    raise TweepyException(f'Failed to parse JSON payload: {e}')
tweepy.errors.TweepyException: Failed to parse JSON payload: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python37\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Python\Python37\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Python\Python37\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Python\Python37\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "pouchmentions.py", line 1154, in <module>
    pouch.run().run(sys.argv[2])
  File "pouchmentions.py", line 1127, in run
    self.__check_dms(routing_key)
  File "pouchmentions.py", line 1093, in __check_dms
    logging.error('Issues retrieving DMs', str(error))
Message: 'Issues retrieving DMs'
Arguments: ('Failed to parse JSON payload: Expecting value: line 1 column 1 (char 0)',)
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\tweepy\parsers.py", line 37, in parse
    json = json_lib.loads(payload)
  File "C:\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pouchmentions.py", line 1154, in <module>
    pouch.run().run(sys.argv[2])
  File "pouchmentions.py", line 1127, in run
    self.__check_dms(routing_key)
  File "pouchmentions.py", line 1095, in __check_dms
    raise error
  File "pouchmentions.py", line 1039, in __check_dms
    self.mention_platform.delete_dm(id = id)
  File "pouchmentions.py", line 562, in delete_dm
    self.__api.delete_direct_message(id = id)
  File "C:\Python\Python37\lib\site-packages\tweepy\api.py", line 3183, in delete_direct_message
    ), id=id, **kwargs
  File "C:\Python\Python37\lib\site-packages\tweepy\api.py", line 273, in request
    payload_type=payload_type, return_cursors=return_cursors
  File "C:\Python\Python37\lib\site-packages\tweepy\parsers.py", line 39, in parse
    raise TweepyException(f'Failed to parse JSON payload: {e}')
tweepy.errors.TweepyException: Failed to parse JSON payload: Expecting value: line 1 column 1 (char 0)

**I checked and it is deleting the DM but it is throwing that exception after deleting it.**

**Comment by Harmon758** [comment]
This was specific to `JSONParser` and should be fixed with https://github.com/tweepy/tweepy/commit/e854138dcecc223fac1038704ec0d9266037217b now.

In the future, please provide the relevant code or a reproducible example.

For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.
