### ISSUE TITLE
453 forbidden

### ISSUE THREAD

**Issue by ihabpalamino** [tweepy/tweepy#2144]
### Summary

i am new at tweepy

### Reproduction Steps

this is my code import datetime
import tweepy

# API credentials (replace with your own)
consumer_key = 'api token'
consumer_secret = 'api secret token'
bearer_token = 'bearer token'

# Authenticate to Twitter API
auth = tweepy.AppAuthHandler(consumer_key, consumer_secret)

api = tweepy.API(auth, wait_on_rate_limit=True)

def scrape_tweets(username, since_date, until_date):
    # Get user's tweets
    tweets = tweepy.Cursor(api.user_timeline, screen_name=username,
                           tweet_mode='extended', include_rts=False,
                           exclude_replies=True).items()

    for tweet in tweets:
        if tweet.created_at >= since_date and tweet.created_at <= until_date:
            print(tweet.created_at, tweet.full_text)

# Example usage
username = '2MInteractive'
since_date = datetime.datetime(2023, 7, 1, 0, 0, 0)  # Replace with your start date
until_date = datetime.datetime(2023, 7, 11, 23, 59, 59)  # Replace with your end date

scrape_tweets(username, since_date, until_date)
 and i havev got this error

Traceback (most recent call last):
  File "C:\Users\HP Probook\PycharmProjects\firstproject\TikTokScrap.py", line 75, in <module>
    scrape_tweets(username, since_date, until_date)
  File "C:\Users\HP Probook\PycharmProjects\firstproject\TikTokScrap.py", line 65, in scrape_tweets
    for tweet in tweets:
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\tweepy\cursor.py", line 86, in __next__
    return self.next()
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\tweepy\cursor.py", line 286, in next
    self.current_page = next(self.page_iterator)
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\tweepy\cursor.py", line 86, in __next__
    return self.next()
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\tweepy\cursor.py", line 167, in next
    data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kwargs)
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\tweepy\api.py", line 33, in wrapper
    return method(*args, **kwargs)
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\tweepy\api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\tweepy\api.py", line 414, in user_timeline
    return self.request(
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\tweepy\api.py", line 271, in request
    raise Forbidden(resp)
tweepy.errors.Forbidden: 403 Forbidden
453 - You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product

### Expected Results

get tweets by date and username 

### Actual Results

tweepy.errors.Forbidden: 403 Forbidden
453 - You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product

### Twitter API Access Plan

Free

### Tweepy Version

 4.14.0

### Checklist

- [X] I have searched for duplicate issues.
- [X] If applicable, I have shown the entire traceback.
- [X] If applicable, I have removed any visible credentials from my code and/or screenshots.

**Comment by russelgauthier** [comment]
Same issue here & went up to the highest level account, setup a prod-level app, reset all of the credentials. Couldn't find a fix unfortunately. I was following a tutorial and their source code was the same as what I created. If I put the wrong credential for one of the variables, the message indicated that, so it seems to be authenticating at least. The message is in regard to authorization, permission levels, etc.

Hopefully, this'll get fixed. Thanks.

**Comment by russelgauthier** [comment]
This only occurs for me when trying the non-v2 version of the API. When I used Client instead of API, and v2, it worked fine. Same credentials. 

Look at: [Twitter v2 + Tweepy v4 tutorial](https://dev.to/twitterdev/a-comprehensive-guide-for-using-the-twitter-api-v2-using-tweepy-in-python-15d9)

**Comment by uralozden** [comment]
it's not working now

**Comment by finaldie** [comment]
Same, it's not working since 10 hours ago. It looks like that's due to some unknown updates from Twitter side. If yes, not sure whether we will have a "free" solution... :(

**Comment by ihabpalamino** [comment]
any updates or news?

**Comment by Harmon758** [comment]
As the error indicates, that Twitter API v1.1 endpoint is not available with Free access.
https://twittercommunity.com/t/announcing-new-access-tiers-for-the-twitter-api/188728
https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api
https://developer.twitter.com/en

For code block usage, see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

In the future, please make sure to fill out the issue form correctly.

@russelgauthier
>  The message is in regard to authorization, permission levels, etc.

No, this error is due to API access, as the error indicates.

@finaldie
> It looks like that's due to some unknown updates from Twitter side. 

No, this has been known since 3-4 months ago.
