### ISSUE TITLE
create_tweet() on premium+ account limits tweet length

### ISSUE THREAD

**Issue by narodnik** [tweepy/tweepy#2197]
### Summary

create_tweet() on premium+ account limits tweet length

### Reproduction Steps

I have a premium+ account with the Free api version.

```python
import tweepy
from twit import *

def get_twitter_conn_v2(api_key, api_key_secret, access_token, access_token_secret) -> tweepy.Client:
    client = tweepy.Client(
        consumer_key=api_key,
        consumer_secret=api_key_secret,
        access_token=access_token,
        access_token_secret=access_token_secret,
    )

    return client

client_v2 = get_twitter_conn_v2(api_key, api_key_secret, access_token, access_token_secret)

msg = open("msg.txt", "r").read()

client_v2.create_tweet(text=msg, media_ids=[])


```

### Expected Results

post tweet

### Actual Results

```
Traceback (most recent call last):
  File "/home/xyz/src/stuff/twat/test2.py", line 32, in <module>
    client_v2.create_tweet(text=msg, media_ids=[media1_id, media2_id])
  File "/home/xyz/.local/lib/python3.12/site-packages/tweepy/client.py", line 835, in create_tweet
    return self._make_request(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/xyz/.local/lib/python3.12/site-packages/tweepy/client.py", line 129, in _make_request
    response = self.request(method, route, params=request_params,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xyz/.local/lib/python3.12/site-packages/tweepy/client.py", line 96, in request
    raise BadRequest(response)
tweepy.errors.BadRequest: 400 Bad Request
Your Tweet text is too long. For more information on how Twitter determines text length see https://github.com/twitter/twitter-text.

```

### Twitter API Access Plan

Free

### Tweepy Version

Version: 4.14.0

### Checklist

- [X] I have searched for duplicate issues.
- [ ] If applicable, I have shown the entire traceback.
- [ ] If applicable, I have removed any visible credentials from my code and/or screenshots.

**Comment by narodnik** [comment]
https://devcommunity.x.com/t/how-to-post-280-4000-characters-via-api-v2/191156
