### ISSUE TITLE
syntax error when importing tweepy

### ISSUE THREAD

**Issue by LucaCoppola** [tweepy/tweepy#2203]
### Summary

Whenever I run my program, that imports tweepy, I get a SyntaxError 

### Reproduction Steps

I'm trying to learn something about twitter scraping, so I went ahead and installed tweepy to test things. I wanted to print the first 10 posts of my timeline like this:
```python
import tweepy
from tweepy import OAuthHandler
 
auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)
 
api = tweepy.API(auth)

for status in tweepy.Cursor(api.home_timeline).items(10):
    print(status.text) 
```
I have defined my keys as strings with the key inside of each string.

### Minimal Reproducible Example

```python
import tweepy
```

### Expected Results

I wanted my program to simply print the first ten posts of my personal timeline.

### Actual Results

Instead I got this Error:
```python
Traceback (most recent call last):
  File "C:\Users\FireLuc33\coding_projects\python projects\twitter scraper\main.py", line 1, in <module>
    import tweepy
  File "C:\Users\FireLuc33\AppData\Local\Programs\Python\Python310\lib\site-packages\tweepy\__init__.py", line 17, in <module>
    from tweepy.streaming import Stream, StreamListener
  File "C:\Users\FireLuc33\AppData\Local\Programs\Python\Python310\lib\site-packages\tweepy\streaming.py", line 340
    def _start(self, async):
                     ^^^^^
SyntaxError: invalid syntax
```

### Twitter API Access Plan

Free

### Tweepy Version

3.3.0

### Checklist

- [X] I have searched for duplicate issues.
- [ ] If applicable, I have shown the entire traceback.
- [ ] If applicable, I have removed any visible credentials from my code and/or screenshots.

**Comment by dmitryon** [comment]
tweepy 3.3.0 does not support python 3.7+. Why don't you use the recent tweepy 4.14.0?

**Comment by joshthecoder** [comment]
Recommend using latest tweepy version to resolve.
