### ISSUE TITLE
Streaming.py crash Incomplete Read

### ISSUE THREAD

**Issue by pchai** [tweepy/tweepy#242]
I've been using tweepy streaming to collect tweets for nearly one month, and this is the second time I received this error. Does anyone know why I am getting this error? Actually, I saw this issue before(streaming.py crash), but it's closed. I am wandering why do I still get this error? 
Thank you for your help!

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "twitterstreamtomongodb.py", line 255, in run
    self.stream.filter(track=[self.searchterm])
  File "/Library/Python/2.7/site-packages/tweepy/streaming.py", line 229, in filter
    self._start(async)
  File "/Library/Python/2.7/site-packages/tweepy/streaming.py", line 172, in _start
    self._run()
  File "/Library/Python/2.7/site-packages/tweepy/streaming.py", line 117, in _run
    self._read_loop(resp)
  File "/Library/Python/2.7/site-packages/tweepy/streaming.py", line 165, in _read_loop
    self.on_closed(resp)
  File "/Library/Python/2.7/site-packages/tweepy/streaming.py", line 177, in on_closed
    self._start(async)
  File "/Library/Python/2.7/site-packages/tweepy/streaming.py", line 172, in _start
    self._run()
  File "/Library/Python/2.7/site-packages/tweepy/streaming.py", line 117, in _run
    self._read_loop(resp)
  File "/Library/Python/2.7/site-packages/tweepy/streaming.py", line 150, in _read_loop
    c = resp.read(1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 541, in read
    return self._read_chunked(amt)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 586, in _read_chunked
    raise IncompleteRead(''.join(value))
IncompleteRead: IncompleteRead(0 bytes read)

**Comment by Harmon758** [comment]
Duplicate of #237.
This seems to have been fixed with https://github.com/tweepy/tweepy/commit/fae9091486bd5e1f7bc7ee0bf7c30651b2086462 (#498), but was reverted with https://github.com/tweepy/tweepy/commit/34af675c8e24b5176dae276342126fb52816ae6e, due to https://github.com/tweepy/tweepy/issues/501.
As for why this occurs, see #448.
