### ISSUE TITLE
Uncaught error when disconnecting async Stream

### ISSUE THREAD

**Issue by pikeas** [tweepy/tweepy#405]
```
# auth and listener configured normally
stream = Stream(auth, listener)
stream.filter(track=[...], async=True)
stream.disconnect()
```

This throws an exception:

In [7]: Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/pikeas/.virtualenvs/play/lib/python2.7/site-packages/tweepy/streaming.py", line 173, in _run
    self._read_loop(resp)
  File "/Users/pikeas/.virtualenvs/play/lib/python2.7/site-packages/tweepy/streaming.py", line 226, in _read_loop
    self._data(next_status_obj)
  File "/Users/pikeas/.virtualenvs/play/lib/python2.7/site-packages/tweepy/streaming.py", line 203, in _data
    if self.listener.on_data(data) is False:
  File "/Users/pikeas/Documents/Code/play/play_django/frankie/twit.py", line 33, in on_data
    if 'in_reply_to_status_id' in data:
TypeError: argument of type 'int' is not iterable

**Comment by pikeas** [comment]
Cleaning up this old issue. PR was https://github.com/tweepy/tweepy/pull/407
