### ISSUE TITLE
image/x-png, image/pjpeg MIME types upload problem in Windows

### ISSUE THREAD

**Issue by szolotykh** [tweepy/tweepy#423]
Function: update_with_media
OS: Windows

Traceback (most recent call last):
  File "twitter-post.py", line 32, in <module>
    api.update_with_media(imagePath)
  File "build\bdist.win32\egg\tweepy\api.py", line 98, in update_with_media
  File "build\bdist.win32\egg\tweepy\api.py", line 733, in _pack_image
tweepy.error.TweepError: Invalid file type for image: image/pjpeg

**Comment by thirumoorthir** [comment]
tried with different format , same problem , not able to solve it
