### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by skrew** [tweepy/tweepy#436]
Hi,

Using streaming.py, sometimes i got this crash:

```
Exception in thread Thread-61:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tweepy-2.3-py2.7.egg/tweepy/streaming.py", line 165, in _run
    self._read_loop(resp)
  File "/usr/local/lib/python2.7/dist-packages/tweepy-2.3-py2.7.egg/tweepy/streaming.py", line 215, in _read_loop
    for d in resp.iter_content():
  File "/usr/local/lib/python2.7/dist-packages/requests-2.2.1-py2.7.egg/requests/utils.py", line 341, in iter_slices
    while pos < len(string):
TypeError: object of type 'bool' has no len()
```

Before looking most forward, I don't know if this bug come from requests or tweepy ? What do you think ?

**Comment by Harmon758** [comment]
This was an issue with requests, https://github.com/kennethreitz/requests/issues/2240, that has been resolved with https://github.com/kennethreitz/requests/commit/65cdccb70f79443b868853c5543e65b2610452f7 (https://github.com/kennethreitz/requests/pull/2241) as part of requests v2.4.2, and Tweepy now requires requests>=2.11.1.
