### ISSUE TITLE
TweepError: Failed to send request: must be _socket.socket, not socket

### ISSUE THREAD

**Issue by krishnaiitd** [tweepy/tweepy#483]
Hello,

I am trying to fetch tweets using tweepy in Google App Engine and getting the following error

```
INFO     2014-08-24 14:29:36,162 connectionpool.py:695] Starting new HTTPS connection (1):         api.twitter.com
ERROR    2014-08-24 14:29:36,584 webapp2.py:1528] Failed to send request: must be _socket.socket, not socket
Traceback (most recent call last):
  File "/Users/krishna/google-cloud-sdk/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
        rv = self.handle_exception(request, response, e)
  File "/Users/krishna/google-cloud-sdk/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
        rv = self.router.dispatch(request, response)
  File "/Users/krishna/google-cloud-sdk/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
        return route.handler_adapter(request, response)
  File "/Users/krishna/google-cloud-sdk/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
        return handler.dispatch()
  File "/Users/krishna/google-cloud-sdk/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
        return self.handle_exception(e, self.app.debug)
  File "/Users/krishna/google-cloud-sdk/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
        return method(*args, **kwargs)
  File "/Users/krishna/Documents/DATASCI/twitterapi/analyzetweets/main.py", line 52, in post
        tweetTextCotainer = THandler.getTweetsText()
  File "/Users/krishna/Documents/DATASCI/twitterapi/analyzetweets/main.py", line 84, in getTweetsText
        for tweet in c.items():
  File "tweepy/tweepy/cursor.py", line 181, in next
        self.current_page = self.page_iterator.next()
  File "tweepy/tweepy/cursor.py", line 99, in next
        data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kargs)
  File "tweepy/tweepy/binder.py", line 209, in _call
        return method.execute()
   File "tweepy/tweepy/binder.py", line 160, in execute
        raise TweepError('Failed to send request: %s' % e)
  TweepError: Failed to send request: must be _socket.socket, not socket
    ERROR    2014-08-24 14:29:36,590 cgi.py:121] Traceback (most recent call last):
  File "/Users/krishna/Documents/DATASCI/twitterapi/analyzetweets/main.py", line 113, in main
        run_wsgi_app(application)
  File "/Users/krishna/google-cloud-sdk/google-cloud-sdk/platform/google_appengine/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
        run_bare_wsgi_app(add_wsgi_middleware(application))
  File "/Users/krishna/google-cloud-sdk/google-cloud-    sdk/platform/google_appengine/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
    result = application(env, _start_response)
  File "/Users/krishna/google-cloud-sdk/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1519, in __call__
        response = self._internal_error(e)
  File "/Users/krishna/google-cloud-sdk/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
        rv = self.handle_exception(request, response, e)
  File "/Users/krishna/google-cloud-sdk/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
        rv = self.router.dispatch(request, response)
  File "/Users/krishna/google-cloud-sdk/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
        return route.handler_adapter(request, response)
  File "/Users/krishna/google-cloud-sdk/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
        return handler.dispatch()
  File "/Users/krishna/google-cloud-sdk/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
        return self.handle_exception(e, self.app.debug)
  File "/Users/krishna/google-cloud-sdk/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/Users/krishna/Documents/DATASCI/twitterapi/analyzetweets/main.py", line 52, in post
        tweetTextCotainer = THandler.getTweetsText()
  File "/Users/krishna/Documents/DATASCI/twitterapi/analyzetweets/main.py", line 84, in         getTweetsText
        for tweet in c.items():
  File "tweepy/tweepy/cursor.py", line 181, in next
            self.current_page = self.page_iterator.next()
  File "tweepy/tweepy/cursor.py", line 99, in next
        data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kargs)
  File "tweepy/tweepy/binder.py", line 209, in _call
        return method.execute()
  File "tweepy/tweepy/binder.py", line 160, in execute
        raise TweepError('Failed to send request: %s' % e)
        TweepError: Failed to send request: must be _socket.socket, not socket
```

**Comment by nicolaerusan** [comment]
I've encountered the same error with _socket.socket when developing locally, although it works fine when actually deploying to App Engine. Has anyone found a good workaround for this when developing locally, that doesn't require modifications that may break production?

I came across this thread in the Github issue which seems to be related to similar issues (SSL?):
https://github.com/stripe/stripe-python/issues/73

**Comment by danielchatfield** [comment]
You can fix this by following this: https://stackoverflow.com/questions/16192916/importerror-no-module-named-ssl-with-dev-appserver-py-from-google-app-engine/16937668#16937668

**Comment by nicolaerusan** [comment]
@danielchatfield thanks for the input on this! I ended up using the workaround mentioned to get it working.
