### ISSUE TITLE
TweepError: Failed to send request: local variable 'auth'

### ISSUE THREAD

**Issue by francocorreasosa** [tweepy/tweepy#519]
Hi, I got `TweepError: Failed to send request: local variable 'auth' referenced before assignment` when i do

```
CONSUMER_KEY = "(removed)"
CONSUMER_SECRET = "(removed)"
ACCESS_KEY = "893312988-(removed)"
ACCESS_SECRET = "(removed)"
authid = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
authid.set_access_token(ACCESS_KEY, ACCESS_SECRET)
api = tweepy.API(authid)

user = tweepy.api.get_user("twitter")
timeline = api.user_timeline(screen_name=user, include_rts=True, count=100)
```

Error detail:

```
INFO     2014-12-06 19:32:38,765 binder.py:102] PARAMS: {'id': 'twitter'}
ERROR    2014-12-06 19:32:38,766 app.py:1423] Exception on / [GET]
Traceback (most recent call last):
  File "/Users/franco/PycharmProjects/flaskcourse/lib/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/franco/PycharmProjects/flaskcourse/lib/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/franco/PycharmProjects/flaskcourse/lib/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/franco/PycharmProjects/flaskcourse/lib/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/franco/PycharmProjects/flaskcourse/lib/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/franco/PycharmProjects/flaskcourse/flaskcourse.py", line 29, in hello_world
    return render_template("index.html", tweet=getTweetCount())
  File "/Users/franco/PycharmProjects/flaskcourse/flaskcourse.py", line 18, in getTweetCount
    user = tweepy.api.get_user("twitter")
  File "/Users/franco/PycharmProjects/flaskcourse/lib/tweepy/binder.py", line 235, in _call
    return method.execute()
  File "/Users/franco/PycharmProjects/flaskcourse/lib/tweepy/binder.py", line 185, in execute
    raise TweepError('Failed to send request: %s' % e)
TweepError: Failed to send request: local variable 'auth' referenced before assignment
```

**Comment by TimothyBramlett** [comment]
Thanks!  helped me as well!  following the documentation and this confused me.

**Comment by beatorizu** [comment]
This worked to me. Thanks a lot!! ^^
