### ISSUE TITLE
Only unicode objects are escapable.

### ISSUE THREAD

**Issue by zhao-ji** [tweepy/tweepy#523]
My requeirements is all satisfied, why this happens?

Traceback (most recent call last):
  File "twi.py", line 16, in <module>
    api.update_status(u"hello world")
  File "/usr/local/lib/python2.7/dist-packages/tweepy/binder.py", line 235, in _call
    return method.execute()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/binder.py", line 185, in execute
    raise TweepError('Failed to send request: %s' % e)
tweepy.error.TweepError: Failed to send request: Only unicode objects are escapable. Got <generator object <genexpr> at 0xb7050cd4> of type <type 'generator'>.

Traceback (most recent call last):
  File "twi.py", line 16, in <module>
    api.update_status("hello world")
  File "/usr/local/lib/python2.7/dist-packages/tweepy/binder.py", line 235, in _call
    return method.execute()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/binder.py", line 185, in execute
    raise TweepError('Failed to send request: %s' % e)
tweepy.error.TweepError: Failed to send request: Only unicode objects are escapable. Got <generator object <genexpr> at 0xb6fb0cd4> of type <type 'generator'>.

this is my code:
auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = API(auth)

api.update_status("hello world")

**Comment by jhovanic** [comment]
Is there any update on this issue ? I'm getting this error too:

`TweepError: Failed to send request: Only unicode objects are escapable. Got None of type <type 'NoneType'>`

**Comment by Dosentti** [comment]
This fix does not work for me. 
stacktrace says the following: 
```
Environment:


Request Method: GET
Request URL: http://0.0.0.0:5000/

Django Version: 1.11.6
Python Version: 3.6.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'whitenoise.runserver_nostatic',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'nonobot']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/tweepy/binder.py" in execute
  187.                                                 proxies=self.api.proxy)

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/requests/sessions.py" in request
  494.         prep = self.prepare_request(req)

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/requests/sessions.py" in prepare_request
  437.             hooks=merge_hooks(request.hooks, self.hooks),

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/requests/models.py" in prepare
  309.         self.prepare_auth(auth, url)

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/requests/models.py" in prepare_auth
  540.             r = auth(self)

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/requests_oauthlib/oauth1_auth.py" in __call__
  88.                 unicode(r.url), unicode(r.method), None, r.headers)

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/oauthlib/oauth1/rfc5849/__init__.py" in sign
  314.             ('oauth_signature', self.get_oauth_signature(request)))

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/oauthlib/oauth1/rfc5849/__init__.py" in get_oauth_signature
  129.         uri, headers, body = self._render(request)

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/oauthlib/oauth1/rfc5849/__init__.py" in _render
  211.                 request.oauth_params, request.headers, realm=realm)

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/oauthlib/oauth1/rfc5849/utils.py" in wrapper
  32.         return target(params, *args, **kwargs)

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/oauthlib/oauth1/rfc5849/parameters.py" in prepare_headers
  59.         escaped_value = utils.escape(value)

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/oauthlib/oauth1/rfc5849/utils.py" in escape
  57.                          'Got %r of type %s.' % (u, type(u)))

During handling of the above exception (Only unicode objects are escapable. Got None of type <class 'NoneType'>.), another exception occurred:

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/media/viljami/projects/nonobot/src/nonobot/nonobot/views.py" in get_tweets
  15.     tweet_list = query_twitter_api(twitter_api, search_string, rpp)

File "/media/viljami/projects/nonobot/src/nonobot/nonobot/views.py" in query_twitter_api
  32.     tweets = twitter_api.search(search_string, rpp=rpp)

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/tweepy/binder.py" in _call
  245.             return method.execute()

File "/home/viljami/.local/share/virtualenvs/nonobot-2cwFijFz/lib/python3.6/site-packages/tweepy/binder.py" in execute
  189.                     raise TweepError('Failed to send request: %s' % e)

Exception Type: TweepError at /
Exception Value: Failed to send request: Only unicode objects are escapable. Got None of type <class 'NoneType'>.

```

**Comment by Shemahmforash** [comment]
Did anyone manage to solve this issue? It's still happening for me with django 2.0.7 and python 3.6.

When following the auth tutorial http://tweepy.readthedocs.io/en/v3.6.0/auth_tutorial.html, I manage to get the request token successfully and after redirecting the user to the redirect_url I can algo get the verifier, but after setting:

```
auth.request_token = {
        'oauth_token': token,
        'oauth_token_secret': verifier
    }
```
when I try to do: 

```
auth.get_access_token(verifier)
```

I get the same error as described in this issue:

```
File "/usr/local/lib/python3.6/site-packages/tweepy/auth.py", line 107, in get_access_token
    raise TweepError(e)
tweepy.error.TweepError: Only unicode objects are escapable. Got {'oauth_token': 'xxxxxxxxx', 'oauth_token_secret': 'xxxxxxxx', 'oauth_callback_confirmed': 'true'} of type <class 'dict'>.
```

Any ideas how to fix this? Thank you.

**Comment by moderatelyfunctional** [comment]
@Shemahmforash if you're still stuck, 
```
auth.request_token = {
      'oauth_token': request.GET.get('oauth_token')
      'oauth_token_secret': request.GET.get('oauth_token_verifier')
}
```
The bearer token is obsolete in the newer version of the Twitter API.

**Comment by ale-cristofori** [comment]
@moderatelyfunctional 
Are you sure that code works...?

Btw I am still stuck in this too, getting the same error message

**Comment by arska** [comment]
@ale-cristofori had the same problem, fixed it with https://github.com/arska/tweepy/commit/d416ba84f037fefb5a424fe81bf0d91a1ce22b02
