### ISSUE TITLE
UnicodeDecodeError using media endpoints

### ISSUE THREAD

**Issue by andrewbonney** [tweepy/tweepy#550]
I've just upgraded from Tweepy v2.3 to v3.2 (Python 2.7). I'm having some issues using the API endpoints update_with_media and media_upload following the change. Upon calling either of these with an image location I end up with an exception (TweepError) which appears to be coming from the call to 'self.session.request' in binder.py.

The error received is:

```
Failed to send request: 'ascii' codec can't decode byte 0x89 in position 181: ordinal not in range(128)
```

Adding a traceback into the exception handler produced the following:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tweepy/binder.py", line 188, in execute
    proxies=self.api.proxy)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 542, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 367, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 827, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 181: ordinal not in range(128)
```

**Comment by bearsylla** [comment]
I am having similar problem on both python2 and python3 on Debian Testing using the tweepy packages from the debian repo.

When using python2 with python-tweepy package (version  3.5.0-1), the error is as follow:

```
Traceback (most recent call last):
  File "./twitter.py", line 68, in <module>
    api.update_with_media('/home/bear/vps/twitterbot/blkchart.png', price_text)
  File "/usr/lib/python2.7/dist-packages/tweepy/api.py", line 232, in update_with_media
    )(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tweepy/binder.py", line 245, in _call
    return method.execute()
  File "/usr/lib/python2.7/dist-packages/tweepy/binder.py", line 189, in execute
    raise TweepError('Failed to send request: %s' % e)
tweepy.error.TweepError: Failed to send request: 'ascii' codec can't decode byte 0x89 in position 136: ordinal not in range(128)
```

And with python3-tweepy (version  3.5.0-1)

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tweepy/binder.py", line 187, in execute
    proxies=self.api.proxy)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3/dist-packages/requests/models.py", line 297, in prepare
    self.prepare_auth(auth, url)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 490, in prepare_auth
    r = auth(self)
  File "/usr/lib/python3/dist-packages/requests_oauthlib/oauth1_auth.py", line 70, in __call__
    r.url = to_native_str(r.url)
  File "/usr/lib/python3/dist-packages/requests_oauthlib/oauth1_auth.py", line 14, in to_native_str
    return string.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./twitter.py", line 68, in <module>
    api.update_with_media('/home/bear/vps/twitterbot/blkchart.png', price_text)
  File "/usr/lib/python3/dist-packages/tweepy/api.py", line 232, in update_with_media
    )(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/tweepy/binder.py", line 245, in _call
    return method.execute()
  File "/usr/lib/python3/dist-packages/tweepy/binder.py", line 189, in execute
    raise TweepError('Failed to send request: %s' % e)
tweepy.error.TweepError: Failed to send request: 'str' object has no attribute 'decode'
```

However, I managed to solve the problem by removing all the tweepy package from the apt repo, then installing tweepy via pip3

**Comment by Seykotron** [comment]
@bearsylla thank you! it worked for me too! 👍

**Comment by Ueland** [comment]
Can confirm that this issue still appears in Ubuntu 16.04.2 LTS, perhaps something for the package maintainer to get fixed.

@bearsylla`s fix works for me to.

**Comment by Harmon758** [comment]
This seems to have been an issue with requests. See #687.
