### ISSUE TITLE
Error in importing tweepy

### ISSUE THREAD

**Issue by aaloy** [tweepy/tweepy#6]
## In [1]: import tweepy

ImportError                               Traceback (most recent call last)

/tmp/<ipython console> in <module>()

/usr/local/lib/python2.6/dist-packages/tweepy-1.3-py2.6.egg/tweepy/**init**.py in <module>()
     12 from tweepy.models import Status, User, DirectMessage, Friendship, SavedSearch, SearchResult, models
     13 from tweepy.error import TweepError
---> 14 from tweepy.api import API
     15 from tweepy.cache import Cache, MemoryCache, FileCache
     16 from tweepy.auth import BasicAuthHandler, OAuthHandler

/usr/local/lib/python2.6/dist-packages/tweepy-1.3-py2.6.egg/tweepy/api.py in <module>()
      6 import mimetypes
      7 
----> 8 from tweepy.binder import bind_api
      9 from tweepy.error import TweepError
     10 from tweepy.parsers import *

/usr/local/lib/python2.6/dist-packages/tweepy-1.3-py2.6.egg/tweepy/binder.py in <module>()
      2 # Copyright 2009 Joshua Roesslein

```
  3 # See LICENSE
```

----> 4 import http.client
      5 import urllib.request, urllib.parse, urllib.error
      6 import time

ImportError: No module named http.client

**Comment by pranjal21** [comment]
import tweepy
[ showing this error]


Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import tweepy
  File "C:\Users\Pranjal Gupta\AppData\Local\Programs\Python\Python35\lib\site-packages\tweepy-3.6.0-py3.5.egg\tweepy\__init__.py", line 16, in <module>
    from tweepy.auth import OAuthHandler, AppAuthHandler
  File "C:\Users\Pranjal Gupta\AppData\Local\Programs\Python\Python35\lib\site-packages\tweepy-3.6.0-py3.5.egg\tweepy\auth.py", line 9, in <module>
    from requests_oauthlib import OAuth1Session, OAuth1
  File "C:\Users\Pranjal Gupta\AppData\Local\Programs\Python\Python35\lib\site-packages\requests_oauthlib-0.6.1-py3.5.egg\requests_oauthlib\__init__.py", line 1, in <module>
    from .oauth1_auth import OAuth1
  File "C:\Users\Pranjal Gupta\AppData\Local\Programs\Python\Python35\lib\site-packages\requests_oauthlib-0.6.1-py3.5.egg\requests_oauthlib\oauth1_auth.py", line 6, in <module>
    from oauthlib.common import extract_params
ImportError: No module named 'oauthlib'

**Comment by Harmon758** [comment]
@pranjal21 This is an unrelated issue. Simply install oauthlib first.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
