### ISSUE TITLE
Looking for urllib.parse fix in the latest version of Tweepy

### ISSUE THREAD

**Issue by myloginid** [tweepy/tweepy#608]
Hi,

Is there a way to resolve the below import issue in Tweepy?

>>> import tweepy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/tweepy/__init__.py", line 12, in <module>
    from tweepy.models import Status, User, DirectMessage, Friendship, SavedSearch, SearchResults, ModelFactory, Category
  File "/usr/lib/python2.7/site-packages/tweepy/models.py", line 7, in <module>
    from tweepy.utils import parse_datetime, parse_html_value, parse_a_href
  File "/usr/lib/python2.7/site-packages/tweepy/utils.py", line 10, in <module>
    from six.moves.urllib.parse import quote
ImportError: No module named urllib.parse

Thanks
Manish

**Comment by myloginid** [comment]
Hi.. Any luck on workarounds for the above?.. Thanks, Manish

**Comment by afjlambert** [comment]
This helped: `pip install six --upgrade`

**Comment by smbsimon** [comment]
I'm having the same problem and upgrading six isn't making any progress for me. Anything else to try?

**Comment by guinslym** [comment]
Thks @afjlambert: This helped: pip install six --upgrade
