### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by muthu1086** [tweepy/tweepy#626]
During pip installation got error as below, tried on python 2.6.6 and 2.7.6 on CentOS

Downloading/unpacking tweepy
  Downloading tweepy-3.3.0.tar.gz
  Running setup.py egg_info for package tweepy
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build-root/tweepy/setup.py", line 17, in <module>
        install_reqs = parse_requirements('requirements.txt', session=uuid.uuid1                                        ())
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build-root/tweepy/setup.py", line 17, in <module>

    install_reqs = parse_requirements('requirements.txt', session=uuid.uuid1())

TypeError: parse_requirements() got an unexpected keyword argument 'session'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-root                                        /tweepy
Storing complete log in /root/.pip/pip.log

**Comment by muthu1086** [comment]
Sorry about this issue, my mistake 

didnt go through the older issue.

pip install --upgrade pip had done the trick
