### ISSUE TITLE
Error while using custom ModelParser

### ISSUE THREAD

**Issue by duydo** [tweepy/tweepy#665]
I had a simple custom ModelParser:

``` py
class TweetParser(ModelParser):
    def parse(self, method, payload):
        return json.loads(payload)
```

and use it to construct an API

``` py
_api = tweepy.API(
                auth_handler=self._auth,
                parser=TweetParser()
            )
```

Using this api to get followers_ids of a  user:

``` py
 cur = tweepy.Cursor(
            method=_api.followers_ids,
            user_id=user_id,
            screen_name=screen_name,
            count=count
        )
        try:
            for page in cur.pages():
                yield page
        except (tweepy.TweepError, tweepy.RateLimitError) as e:
            self.logger.error(e)
            raise ServiceErrorException(e)
```

I got the error:

``` py
2015-11-04 06:26:44,869 - Worker - ERROR - too many values to unpack
Traceback (most recent call last):
  File "/home/duy/virtualenvs/***/code/***/jq/worker.py", line 64, in on_message_received
    self.process_job_message(payload)
  File "/home/duy/virtualenvs/***/code/***/jq/worker.py", line 84, in process_job_message
    result = job.run(**kwdict(job_message.get('body', {})))
  File "/home/duy/virtualenvs/***/code/***/jobs/twitter/network_discovery.py", line 12, in run
    for follower_ids in self.twitter_service.get_followers_ids(user_id=sns_id):
  File "/home/duy/virtualenvs/***/code/***/services/twitter.py", line 149, in get_followers_ids
    for page in cur.pages():
  File "/home/duy/virtualenvs/***/local/lib/python2.7/site-packages/tweepy/cursor.py", line 75, in next
    **self.kargs)
ValueError: too many values to unpack
```

Every thing works fine if I don't use a custom ModelParser.

Is it a bug?

**Comment by duydo** [comment]
Have no feedback on this?
