### ISSUE TITLE
More information needed on how to run tests

### ISSUE THREAD

**Issue by ttz21** [tweepy/tweepy#681]
Hi, I'm a first time open source contributor and I'm trying to make a pull request, but I'm having issues running the tests.  I think the documentation could be clearer on how to set up the testing environment, as it's non-trivial for newbies.

After installation, I did `pip install -r test_requirements.txt`

From the tweepy directory I tried to run `nosetests tests/test_api.py`.  This resulted in the following stack trace, which I am unsure of how to resolve.  
# 
## ERROR: Failure: ImportError (No module named http_client)

Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/tinazhang/Documents/GitHub/24PR/tweepy/tests/test_api.py", line 12, in <module>
    from .config import TweepyTestCase, username, use_replay, tape
  File "/Users/tinazhang/Documents/GitHub/24PR/tweepy/tests/config.py", line 3, in <module>
    import vcr
  File "/Library/Python/2.7/site-packages/vcr/**init**.py", line 2, in <module>
    from .config import VCR
  File "/Library/Python/2.7/site-packages/vcr/config.py", line 6, in <module>
    from .cassette import Cassette
  File "/Library/Python/2.7/site-packages/vcr/cassette.py", line 12, in <module>
    from .patch import CassettePatcherBuilder
  File "/Library/Python/2.7/site-packages/vcr/patch.py", line 8, in <module>
    from .stubs import VCRHTTPConnection, VCRHTTPSConnection
  File "/Library/Python/2.7/site-packages/vcr/stubs/**init**.py", line 9, in <module>
    from six.moves.http_client import (
ImportError: No module named http_client

---

Ran 1 test in 0.001s

FAILED (errors=1)

**Comment by awlamb** [comment]
just to clarify for myself, you did:

git clone https://github.com/tweepy/tweepy.git
cd tweepy
python setup.py install
pip install -r test_requirements.txt
nosetests

is that correct?

**Comment by Harmon758** [comment]
I've greatly simplified the testing process (https://github.com/tweepy/tweepy/issues/1217#issuecomment-513665600) and have now added documentation for how to run tests at https://tweepy.readthedocs.io/en/latest/running_tests.html (https://github.com/tweepy/tweepy/commit/0aa7310bc88321248628f4f9acb5fa5f46cfbcf0).
