### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by kodeine** [tweepy/tweepy#698]
i've been getting this error for a while.

``` python
Traceback (most recent call last):
  File "engine/twitter.py", line 139, in <module>
    stream.filter(track=['#blood',], languages=['en'])
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 445, in filter
    self._start(async)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 263, in _run
    self._read_loop(resp)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 313, in _read_loop
    line = buf.read_line().strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by kodeine** [comment]
Another one,

```python
Traceback (most recent call last):
  File "engine/twitter.py", line 139, in <module>
    stream.filter(track=['#blood',], languages=['en'])
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 445, in filter
    self._start(async)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 263, in _run
    self._read_loop(resp)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 324, in _read_loop
    self._data(next_status_obj)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 297, in _data
    if self.listener.on_data(data) is False:
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 50, in on_data
    data = json.loads(raw_data)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

**Comment by rxcomm** [comment]
This patch fixes it for me.
```
diff --git a/tweepy/streaming.py b/tweepy/streaming.py
index ad7944c..6818f58 100644
--- a/tweepy/streaming.py
+++ b/tweepy/streaming.py
@@ -310,7 +310,10 @@ class Stream(object):
         while self.running and not resp.raw.closed:
             length = 0
             while not resp.raw.closed:
-                line = buf.read_line().strip()
+                try:
+                    line = buf.read_line().strip()
+                except AttributeError:
+                    pass
                 if not line:
                     self.listener.keep_alive()  # keep-alive new lines are expected
                 elif line.isdigit():
```

**Comment by runn1ng** [comment]
I am getting this too. I hope you won't be against it @rxcomm if I add this as a pull request

**Comment by remram44** [comment]
I'm also getting this.

**Comment by runn1ng** [comment]
it's fixed in #694 , nobody is merging PR here

**Comment by patrick-brian-mooney** [comment]
Still affects me. Hoping a new version is posted to PyPI soon!

**Comment by wuhland** [comment]
I just got this error. Somebody please give somebody access to this repo so they can PR and also post to PyPI

**Comment by joshua-barber** [comment]
@Aaron1011 (as you closed the issue) can you clarify if the fix was applied/posted to PyPI?

I've been running a data collection script since January and, checking the logs, its been hitting this issue pretty regularly. Not sure what the commonality is between the erroring tweets either.

**Comment by paulaldana23** [comment]
Hello @joshua-barber,

Were you able to catch the error, at least? I'm thinking of a work around for my project wherein I will just catch this particular error and just restart the stream data collection. Not the nicest solution, but it'll work for me.

Regards,

Paul

**Comment by Harmon758** [comment]
@patrick-brian-mooney @wuhland @joshua-barber @paldana 
This specific fix (https://github.com/tweepy/tweepy/commit/c1eddf1a5788ec4947d3a363dfe165ea599c31fc) was in the [v3.6.0](https://github.com/tweepy/tweepy/releases/tag/v3.6.0) release.
However, the error persisted (see #1026). This was then fixed with https://github.com/tweepy/tweepy/commit/32fa592d4ae535baf6e1cf17658d207fb656b16b (#1027) in [3.7.0](https://github.com/tweepy/tweepy/releases/tag/3.7.0).
