### ISSUE TITLE
another issue

### ISSUE THREAD

**Issue by kodeine** [tweepy/tweepy#726]
``` python
Traceback (most recent call last):
  File "engine/twitter.py", line 91, in <module>
    stream.filter(track=['#hashtag',], languages=['en'])
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 446, in filter
    self._start(async)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 362, in _start
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 264, in _run
    self._read_loop(resp)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 325, in _read_loop
    self._data(next_status_obj)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 298, in _data
    if self.listener.on_data(data) is False:
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 50, in on_data
    data = json.loads(raw_data)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

```

**Comment by kodeine** [comment]
i've been getting this error a lot. Anyone gets this as well?

**Comment by coyote-tango** [comment]
What exactly are you trying to perform?
