### ISSUE TITLE
error with simple "Hello World"

### ISSUE THREAD

**Issue by mrcrocodile556** [tweepy/tweepy#729]
Hi everyone, 
I am trying out a simple "Hello World" tweet however I am facing some errors.
I believe I am using tweepy-3.6.0 and python 2.7.9 (Can anyone suggest how do i check my version of tweepy and python?)

My codes:
```
import tweepy

def get_api(cfg):
  auth = tweepy.OAuthHandler(cfg['consumer_key'], cfg['consumer_secret'])
  auth.set_access_token(cfg['access_token'], cfg['access_token_secret'])
  return tweepy.API(auth)

def main():
  # Fill in the values noted in previous step here
  cfg = { 
    "consumer_key"        : "I PLACED MY KEYS HERE",
    "consumer_secret"     : "I PLACED MY KEYS HERE",
    "access_token"        : "I PLACED MY KEYS HERE",
    "access_token_secret" : "I PLACED MY KEYS HERE" 
    }

  api = get_api(cfg)
  tweet = "Hello, world!"
  status = api.update_status(status=tweet) 

if __name__ == "__main__":
  main()
```

This is a list of errors i get after i run `sudo python twitter.py` 
```
Traceback (most recent call last):
  File "twitter.py", line 23, in <module>
    main()
  File "twitter.py", line 19, in main
    status = api.update_status(status=tweet)
  File "build/bdist.linux-armv7l/egg/tweepy/api.py", line 194, in update_status
  File "build/bdist.linux-armv7l/egg/tweepy/binder.py", line 245, in _call
  File "build/bdist.linux-armv7l/egg/tweepy/binder.py", line 229, in execute
tweepy.error.TweepError: [{u'message': u'Timestamp out of bounds.', u'code': 135}]
```

Thank you in advance!!

**Comment by mrcrocodile556** [comment]
found my solution!

**Comment by chuckoy** [comment]
@mrcrocodile556 It would be nice if you detailed what exactly your problem was and how you solved it if anybody in the future is in a similar situation.
