### ISSUE TITLE
using python shell 3.5.1

### ISSUE THREAD

**Issue by pranjal21** [tweepy/tweepy#746]
import tweepy
[ showing this error]

Traceback (most recent call last):
File "", line 1, in 
import tweepy
File "C:\Users\Pranjal Gupta\AppData\Local\Programs\Python\Python35\lib\site-packages\tweepy-3.6.0-py3.5.egg\tweepy__init__.py", line 16, in 
from tweepy.auth import OAuthHandler, AppAuthHandler
File "C:\Users\Pranjal Gupta\AppData\Local\Programs\Python\Python35\lib\site-packages\tweepy-3.6.0-py3.5.egg\tweepy\auth.py", line 9, in 
from requests_oauthlib import OAuth1Session, OAuth1
File "C:\Users\Pranjal Gupta\AppData\Local\Programs\Python\Python35\lib\site-packages\requests_oauthlib-0.6.1-py3.5.egg\requests_oauthlib__init__.py", line 1, in 
from .oauth1_auth import OAuth1
File "C:\Users\Pranjal Gupta\AppData\Local\Programs\Python\Python35\lib\site-packages\requests_oauthlib-0.6.1-py3.5.egg\requests_oauthlib\oauth1_auth.py", line 6, in 
from oauthlib.common import extract_params
ImportError: No module named 'oauthlib'

**Comment by opendataprincess** [comment]
I'm also getting a similar import error message.

**Comment by dev-techmoe** [comment]
pip install oauthlib

**Comment by Mapleaaa** [comment]
and updated to the newest 3.5 version

**Comment by Harmon758** [comment]
Simply install oauthlib first.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
