### ISSUE TITLE
TypeError: expected string or buffer

### ISSUE THREAD

**Issue by remram44** [tweepy/tweepy#749]
After applying the fix to #576, my program kept crashing regularly. Changing the code for it to display a traceback ([your re-raising](https://github.com/tweepy/tweepy/blob/cd46550b3ef068857f5de9c37bbdd0a72acb7462/tweepy/streaming.py#L294) discards it), this is what I got:

```
Traceback (most recent call last):
  ...
    stream.filter(**kwargs)
  File "venv/local/lib/python2.7/site-packages/tweepy/streaming.py", line 446, in filter
    self._start(async)
  File "venv/local/lib/python2.7/site-packages/tweepy/streaming.py", line 362, in _start
    self._run()
  File "venv/local/lib/python2.7/site-packages/tweepy/streaming.py", line 264, in _run
    self._read_loop(resp)
  File "venv/local/lib/python2.7/site-packages/tweepy/streaming.py", line 325, in _read_loop
    self._data(next_status_obj)
  File "venv/local/lib/python2.7/site-packages/tweepy/streaming.py", line 298, in _data
    if self.listener.on_data(data) is False:
  File "venv/local/lib/python2.7/site-packages/tweepy/streaming.py", line 50, in on_data
    data = json.loads(raw_data)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

I'm running 3.5.0.

**Comment by remram44** [comment]
This is because `ReadBuffer.read_len()` can return `None` (or rather, finish without hitting a return statement).

**Comment by Aaron1011** [comment]
Fixed in https://github.com/tweepy/tweepy/commit/c1eddf1a5788ec4947d3a363dfe165ea599c31fc.
