### ISSUE TITLE
ReadTimeoutError

### ISSUE THREAD

**Issue by remram44** [tweepy/tweepy#750]
Another periodic crash (different from #749): while some network exceptions are caught, it is not the case of `requests.packages.urllib3.exceptions.ReadTimeoutError` and the program errors out.

```
Traceback (most recent call last):
  ...
    stream.filter(**kwargs)
  File "venv/local/lib/python2.7/site-packages/tweepy/streaming.py", line 447, in filter
    self._start(async)
  File "venv/local/lib/python2.7/site-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "venv/local/lib/python2.7/site-packages/tweepy/streaming.py", line 263, in _run
    self._read_loop(resp)
  File "venv/local/lib/python2.7/site-packages/tweepy/streaming.py", line 313, in _read_loop
    line = buf.read_line().strip()
  File "venv/local/lib/python2.7/site-packages/tweepy/streaming.py", line 179, in read_line
    self._buffer += self._stream.read(self._chunk_size)
  File "venv/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 320, in read
    flush_decoder = True
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "venv/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 233, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='stream.twitter.com', port=443): Read timed out.
```

**Comment by Mag-neto** [comment]
I am also getting the same error. Any Help?
`Traceback (most recent call last):
 ......
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 445, in filter
    self._start(async)
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 361, in _start
    self._run()
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 294, in _run
    raise exception
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='stream.twitter.com', port=443): Read timed out.`

**Comment by jondhc** [comment]
@ksajjan have you found what was the problem?

**Comment by jondhc** [comment]
I think this can be solved with a Try-Catch statement, restarting the streaming in case of an error

**Comment by ksajjan** [comment]
yes. I solved it with the help of Try-expect block.

**Comment by BrendanMartin** [comment]
@ksajjan what was your try-except implementation?

**Comment by DarkRedman** [comment]
This can't be always solved with a try catch because when you use it in a for loop you've to put a while error = False and inside the catch set error to True and set it to False in the end of the try which makes it ugly in my opinion, it'd be better to handle it inside the tweepy code and add a flags so it handles it a better way.

Like the flag that don't throw error on ratelimit : wait_on_rate_limit=True
We could use a flag like retry_on_read_timeout=True

**Comment by Harmon758** [comment]
I mistakenly closed this in https://github.com/tweepy/tweepy/commit/4d864ab2220b1c3eea516bbe215948d923a7e936, but `requests.ReadTimeout` is not `urllib3.exceptions.ReadTimeoutError`. I've reverted that commit now with https://github.com/tweepy/tweepy/commit/a588ecac8819232e8badf27aed3959b5cae5fbc2, since `requests.ReadTimeout` subclasses `requests.Timeout`, which is already handled anyway. This issue still persists.

**Comment by Harmon758** [comment]
This should now be resolved with https://github.com/tweepy/tweepy/commit/68e19cc6b9b23d72369ca1520093770eb18a5a9f.

@ksajjan For code block usage, see https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.
