### ISSUE TITLE
Tweepy 3.5.0 with Python 3.5.2 doesn't return any data at all from a stream

### ISSUE THREAD

**Issue by Megalegacy98** [tweepy/tweepy#760]
Python 3.5.2, Tweepy 3.5.0, Windows 8.1

I'm following a tutorial made by sentdex that shows how to stream data from Twitter using tweepy. (His tutorial is in Python 2 but it is pretty easy to Python 3-ify it)

However, when I run the script, it doesn't spit out any data. It hangs until I get a 3-way IncompleteRead exception, or until I do Ctrl+C.

Here is my Listener class code:
`

	class listener(StreamListener):

		def on_date(self,data):
			try:
				print(data)
				save = open('twitDB.csv', 'a')
				save.write(data)
				save.write('\n')
				save.close()
				return True
			except BaseException as e:
				print('failed on data,',str(e))
				time.sleep(5)

		def on_error(self,status):
			print(status)

	auth = OAuthHandler(ckey, csecret)
	auth.set_access_token(atoken,asecret)
	twitterStream = Stream(auth=auth, listener=listener())
	twitterStream.filter(track=["car"]) 

`
As you can see, I have it set up to catch errors and print data out while saving it to a csv, but it doesn't really do anything, just hangs.

Also, for track, I did try to use something less general but it still hanged.

When KeyboardInterrupt is raised:
`

	Traceback (most recent call last):
	  File "C:\Program Files\Python35\lib\site-packages\requests\packages\urllib3\co
	ntrib\pyopenssl.py", line 217, in recv_into
		return self.connection.recv_into(*args, **kwargs)
	  File "C:\Program Files\Python35\lib\site-packages\OpenSSL\SSL.py", line 1352,
	in recv_into
		self._raise_ssl_error(self._ssl, result)
	  File "C:\Program Files\Python35\lib\site-packages\OpenSSL\SSL.py", line 1167,
	in _raise_ssl_error
		raise WantReadError()
	OpenSSL.SSL.WantReadError

	During handling of the above exception, another exception occurred:
	Traceback (most recent call last):
	  File "twittertest.py", line 33, in <module>
		twitterStream.filter(track=["car"])
	  File "C:\Program Files\Python35\lib\site-packages\tweepy\streaming.py", line 4
	45, in filter
		self._start(async)
	  File "C:\Program Files\Python35\lib\site-packages\tweepy\streaming.py", line 3
	61, in _start
		self._run()
	  File "C:\Program Files\Python35\lib\site-packages\tweepy\streaming.py", line 2
	63, in _run
		self._read_loop(resp)
	  File "C:\Program Files\Python35\lib\site-packages\tweepy\streaming.py", line 3
	13, in _read_loop
		line = buf.read_line().strip()
	  File "C:\Program Files\Python35\lib\site-packages\tweepy\streaming.py", line 1
	79, in read_line
		self._buffer += self._stream.read(self._chunk_size)
	  File "C:\Program Files\Python35\lib\site-packages\requests\packages\urllib3\re
	sponse.py", line 310, in read
		data = self._fp.read(amt)
	  File "C:\Program Files\Python35\lib\http\client.py", line 448, in read
		n = self.readinto(b)
	  File "C:\Program Files\Python35\lib\http\client.py", line 478, in readinto
		return self._readinto_chunked(b)
	  File "C:\Program Files\Python35\lib\http\client.py", line 573, in _readinto_ch
	unked
		chunk_left = self._get_chunk_left()
	  File "C:\Program Files\Python35\lib\http\client.py", line 541, in _get_chunk_l
	eft
		chunk_left = self._read_next_chunk_size()
	  File "C:\Program Files\Python35\lib\http\client.py", line 501, in _read_next_c
	hunk_size
		line = self.fp.readline(_MAXLINE + 1)
	  File "C:\Program Files\Python35\lib\socket.py", line 575, in readinto
		return self._sock.recv_into(b)
	  File "C:\Program Files\Python35\lib\site-packages\requests\packages\urllib3\co
	ntrib\pyopenssl.py", line 230, in recv_into
		[self.socket], [], [], self.socket.gettimeout())
	KeyboardInterrupt
`
It's my first time going with a social media API, so I apologize if I'm missing something obvious. Help would be appreciated, thanks.

**Comment by Megalegacy98** [comment]
Never mind, it was a typo with on_data. I put on_date.
