### ISSUE TITLE
How Can I resolve this, I followed the directions of prior issues but it hasn't worked for me. If I have to rollback to 3.2.0 what's the best way?

### ISSUE THREAD

**Issue by DamonRedding** [tweepy/tweepy#825]
```
Traceback (most recent call last):
  File "/Users/damonredding/Downloads/Not Mining my own business/twitter_sentiment.py", line 72, in <module>
    stream.filter(track=['congress'])
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tweepy/streaming.py", line 445, in filter
    self._start(async)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tweepy/streaming.py", line 294, in _run
    raise exception
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tweepy/streaming.py", line 263, in _run
    self._read_loop(resp)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tweepy/streaming.py", line 324, in _read_loop
    self._data(next_status_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tweepy/streaming.py", line 297, in _data
    if self.listener.on_data(data) is False:
```

**Comment by Aaron1011** [comment]
Can you post the full stacktrace? The buttom is cut off.

**Comment by DamonRedding** [comment]
Sorry about that:`https://t.co/SlvSuvHPgs
WU GOAN RUN FOR CONGRESS

HOLY SHIT

HOLY FUCK

OH MY GOD
Traceback (most recent call last):
  File "/Users/damonredding/Downloads/Not Mining my own business/twitter_sentiment.py", line 72, in <module>
    stream.filter(track=['congress'])
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tweepy/streaming.py", line 445, in filter
    self._start(async)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tweepy/streaming.py", line 294, in _run
    raise exception
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tweepy/streaming.py", line 263, in _run
    self._read_loop(resp)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tweepy/streaming.py", line 324, in _read_loop
    self._data(next_status_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tweepy/streaming.py", line 297, in _data
    if self.listener.on_data(data) is False:
  File "/Users/damonredding/Downloads/Not Mining my own business/twitter_sentiment.py", line 31, in on_data
    print (tweet).sentiment.polarity
AttributeError: 'NoneType' object has no attribute 'sentiment'`

**Comment by Harmon758** [comment]
> `print (tweet).sentiment.polarity`

`print` returns `None`, and as the error says, `None` does not have a `sentiment` attribute.

This is not an issue with Tweepy.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
