### ISSUE TITLE
No support for TimeZones

### ISSUE THREAD

**Issue by icarito** [tweepy/tweepy#84]
Traceback (most recent call last):
  File "status.py", line 6, in <module>
    public_tweets = api.public_timeline()
  File "/home/icaro/Proyectos/Coodots Tracker/tweepy/binder.py", line 184, in _call
    return method.execute()
  File "/home/icaro/Proyectos/Coodots Tracker/tweepy/binder.py", line 170, in execute
    result = self.api.parser.parse(self, resp.read())
  File "/home/icaro/Proyectos/Coodots Tracker/tweepy/parsers.py", line 76, in parse
    result = model.parse_list(method.api, json)
  File "/home/icaro/Proyectos/Coodots Tracker/tweepy/models.py", line 39, in parse_list
    results.append(cls.parse(api, obj))
  File "/home/icaro/Proyectos/Coodots Tracker/tweepy/models.py", line 55, in parse
    setattr(status, k, parse_datetime(v))
  File "/home/icaro/Proyectos/Coodots Tracker/tweepy/utils.py", line 17, in parse_datetime
    date = datetime(*(time.strptime(string, '%a %b %d %H:%M:%S +0000 %Y')[0:6]))
  File "/usr/lib/python2.6/_strptime.py", line 454, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib/python2.6/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data 'Sun Feb 27 22:25:40 -0500 2011' does not match format '%a %b %d %H:%M:%S +0000 %Y'

**Comment by Harmon758** [comment]
This should now be fixed with https://github.com/tweepy/tweepy/commit/a5bae83eb60ff1b478c4a39cbd29ffe12155abc8 as part of Tweepy 2.2.
