### ISSUE TITLE
Issue in using tweepy stream API

### ISSUE THREAD

**Issue by pankajgoel22** [tweepy/tweepy#868]
I am getting the error "cannot use a string pattern on a bytes-like object" on the line twitterStream.filter(track=['#python']).

When I use utf-8 encoding, I get the error: "cannot use a string pattern on a bytes-like object"

My tweepy package is: tweepy 3.5.0   py36_0    conda-forge

I am using it with Anaconda Pythin version 3.6.0

The tweepy.API.search(search_term) API works fine for me and returns 15 tweets.

I searched on the net and it seems I am using the API correctly. Can you suggest how I can resolve this issue?

Regards,

Pankaj

**Comment by pankajgoel22** [comment]
Another update. On using the command in Jupyter Notebook (Python 3.6), I am getting this error.

Code:

myStreamListener = listener()
twitterStream = Stream(auth, listener=myStreamListener)
twitterStream.filter(track=['#python'], async=True)

Error:

Exception in thread Thread-6:
Traceback (most recent call last):
  File "D:\Data\Software\Python_Anaconda\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Data\Software\Python_Anaconda\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Data\Software\Python_Anaconda\lib\site-packages\tweepy\streaming.py", line 294, in _run
    raise exception
  File "D:\Data\Software\Python_Anaconda\lib\site-packages\tweepy\streaming.py", line 263, in _run
    self._read_loop(resp)
  File "D:\Data\Software\Python_Anaconda\lib\site-packages\tweepy\streaming.py", line 324, in _read_loop
    self._data(next_status_obj)
  File "D:\Data\Software\Python_Anaconda\lib\site-packages\tweepy\streaming.py", line 297, in _data
    if self.listener.on_data(data) is False:
  File "<ipython-input-19-689153b50d4b>", line 8, in on_data
    t=int(calctime(initime))
NameError: name 'calctime' is not defined

Exception in thread Thread-7:
Traceback (most recent call last):
  File "D:\Data\Software\Python_Anaconda\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Data\Software\Python_Anaconda\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Data\Software\Python_Anaconda\lib\site-packages\tweepy\streaming.py", line 294, in _run
    raise exception
  File "D:\Data\Software\Python_Anaconda\lib\site-packages\tweepy\streaming.py", line 263, in _run
    self._read_loop(resp)
  File "D:\Data\Software\Python_Anaconda\lib\site-packages\tweepy\streaming.py", line 324, in _read_loop
    self._data(next_status_obj)
  File "D:\Data\Software\Python_Anaconda\lib\site-packages\tweepy\streaming.py", line 297, in _data
    if self.listener.on_data(data) is False:
  File "<ipython-input-19-689153b50d4b>", line 8, in on_data
    t=int(calctime(initime))
NameError: name 'calctime' is not defined

**Comment by briley-user** [comment]
I am also receiving the second issue, with very similar code. Any help would be appreciated.

Thank you

**Comment by Harmon758** [comment]
I'm unable to reproduce your first set of errors.
Can you reproduce this using the latest development version of Tweepy and provide full tracebacks and any relevant code?

As for your second error, this is an error in your code in the `on_data` method of your `listener` class and as the error says, `calctime` is not defined.
