### ISSUE TITLE
AttributeError when streaming 

### ISSUE THREAD

**Issue by HawkinsJM** [tweepy/tweepy#869]
I ran a stream for awhile and it stopped working after a couple days due to the following error:

 File "tstreamer.py", line 109, in <module>
    myStream.userstream("with=following")
  File "/mnt/d5ddf659-feb7-4daf-95c6-09797c84aa98/venvs/python2ds/lib/python2.7/site-packages/tweepy/streaming.py", line 394, in userstream
    self._start(async)
  File "/mnt/d5ddf659-feb7-4daf-95c6-09797c84aa98/venvs/python2ds/lib/python2.7/site-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/mnt/d5ddf659-feb7-4daf-95c6-09797c84aa98/venvs/python2ds/lib/python2.7/site-packages/tweepy/streaming.py", line 294, in _run
    raise exception
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by devl00p** [comment]
same bug here with Python3 :

**Comment by melizeche** [comment]
Same here
`
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/marce/comentaBOT/env/lib/python3.4/site-packages/tweepy/streaming.py", line 294, in _run
    raise exception
  File "/home/marce/comentaBOT/env/lib/python3.4/site-packages/tweepy/streaming.py", line 263, in _run
    self._read_loop(resp)
  File "/home/marce/comentaBOT/env/lib/python3.4/site-packages/tweepy/streaming.py", line 313, in _read_loop
    line = buf.read_line().strip()
AttributeError: 'NoneType' object has no attribute 'strip'
`

**Comment by miroli** [comment]
Will this fix ever be pushed to Pypi?

**Comment by olihawkins** [comment]
I just got this too. It's still a live issue.

```shell
Traceback (most recent call last):
  File "twitterd.py", line 792, in run
    userstream.userstream()
  File "/home/web/miniconda3/lib/python3.6/site-packages/tweepy/streaming.py", line 394, in userstream
    self._start(async)
  File "/home/web/miniconda3/lib/python3.6/site-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/home/web/miniconda3/lib/python3.6/site-packages/tweepy/streaming.py", line 294, in _run
    raise exception
  File "/home/web/miniconda3/lib/python3.6/site-packages/tweepy/streaming.py", line 263, in _run
    self._read_loop(resp)
  File "/home/web/miniconda3/lib/python3.6/site-packages/tweepy/streaming.py", line 313, in _read_loop
    line = buf.read_line().strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```
