### ISSUE TITLE
tweepy errror filtering by coordinates

### ISSUE THREAD

**Issue by ptcmarin** [tweepy/tweepy#883]
Traceback (most recent call last):
  File "analisis3.py", line 50, in <module>
    twitterStream.filter(locations=bogota)
  File "/usr/local/lib/python3.6/site-packages/tweepy-3.6.0-py3.6.egg/tweepy/streaming.py", line 450, in filter
  File "/usr/local/lib/python3.6/site-packages/tweepy-3.6.0-py3.6.egg/tweepy/streaming.py", line 364, in _start
  File "/usr/local/lib/python3.6/site-packages/tweepy-3.6.0-py3.6.egg/tweepy/streaming.py", line 297, in _run
  File "/usr/local/lib/python3.6/site-packages/six-1.10.0-py3.6.egg/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/tweepy-3.6.0-py3.6.egg/tweepy/streaming.py", line 266, in _run
  File "/usr/local/lib/python3.6/site-packages/tweepy-3.6.0-py3.6.egg/tweepy/streaming.py", line 323, in _read_loop
tweepy.error.TweepError: Expecting length, unexpected value found

ANY SUGGESTION?

**Comment by wodim** [comment]
Paste your code?

**Comment by Harmon758** [comment]
Closing in favor of #892 

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
