### ISSUE TITLE
Bad Authentication Data code: 215

### ISSUE THREAD

**Issue by neerajpal09** [tweepy/tweepy#905]
Script fails and output is :

`Traceback (most recent call last):
  File "senti.py", line 34, in <module>
    print(api.me().name)
  File "/usr/lib/python2.7/site-packages/tweepy/api.py", line 338, in me
    return self.get_user(screen_name=self.auth.get_username())
  File "/usr/lib/python2.7/site-packages/tweepy/auth.py", line 134, in get_username
    user = api.verify_credentials()
  File "/usr/lib/python2.7/site-packages/tweepy/api.py", line 631, in verify_credentials
    )(**kargs)
  File "/usr/lib/python2.7/site-packages/tweepy/binder.py", line 245, in _call
    return method.execute()
  File "/usr/lib/python2.7/site-packages/tweepy/binder.py", line 229, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{u'message': u'Bad Authentication data.', u'code': 215}]
`

**Comment by Harmon758** [comment]
This means that Twitter rejected your credentials.
Make sure you are using the right credentials and properly [set up authentication](https://tweepy.readthedocs.io/en/latest/auth_tutorial.html).

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
