### ISSUE TITLE
[Request] Provide human-readable logging for already existing status error

### ISSUE THREAD

**Issue by toubou91** [tweepy/tweepy#943]
Hello, 

nice effort!

For an already existing status, the response I get from the API, is like below:

```
Traceback (most recent call last):
  File "tweet.py", line 36, in <module>
    main()
  File "tweet.py", line 32, in main
    status = api.update_status(status=tweet) 
  File "/usr/local/lib/python2.7/site-packages/tweepy/api.py", line 194, in update_status
    )(post_data=post_data, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tweepy/binder.py", line 245, in _call
    return method.execute()
  File "/usr/local/lib/python2.7/site-packages/tweepy/binder.py", line 229, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{u'message': u'Status is a duplicate.', u'code': 187}]
```

Couldn't we just replace the default API's response with a more human friendly error message? Like "You have already posted this tweet".

Regards,
Thodoris Bais

**Comment by fitnr** [comment]
Roll your own:
```python
try:
    api.update_status(status=tweet)
except TweepError as err:
    if err.response[0].code == 187:
        print("You have already posted this tweet")
    else:
        raise
```

**Comment by toubou91** [comment]
I mean, I know I can roll my own, I wanted to see the scope of logging of this project.
