### ISSUE TITLE
Exception after large Search API request

### ISSUE THREAD

**Issue by BrendanMartin** [tweepy/tweepy#944]
After running a Tweepy cursor on the Search API for around 1300 pages, I receive the following exception:

-------------------------------------------------------------------------------------------------------
Tweepy request failed.
Traceback (most recent call last):
  File "C:\Users\...\venv\lib\site-packages\tweepy\binder.py", line 190, in execute
    proxies=self.api.proxy)
  File "C:\Users\...\venv\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\...\venv\lib\site-packages\requests\sessions.py", line 658, in send
    r.content
  File "C:\Users\...\venv\lib\site-packages\requests\models.py", line 823, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/.../collect_tweets.py", line 36, in get_latest_tweets
    result_type='recent').pages():
  File "C:\Users\...\venv\lib\site-packages\tweepy\cursor.py", line 49, in __next__
    return self.next()
  File "C:\Users\...\venv\lib\site-packages\tweepy\cursor.py", line 108, in next
    data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kargs)
  File "C:\Users\...\venv\lib\site-packages\tweepy\binder.py", line 250, in _call
    return method.execute()
  File "C:\Users\...\venv\lib\site-packages\tweepy\binder.py", line 192, in execute
    six.reraise(TweepError, TweepError('Failed to send request: %s' % e), sys.exc_info()[2])
  File "C:\Users\...\venv\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\...\venv\lib\site-packages\tweepy\binder.py", line 190, in execute
    proxies=self.api.proxy)
  File "C:\Users\...\venv\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\...\venv\lib\site-packages\requests\sessions.py", line 658, in send
    r.content
  File "C:\Users\...\venv\lib\site-packages\requests\models.py", line 823, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
tweepy.error.TweepError: Failed to send request: 

Process finished with exit code 0

---------------------------------------------------------------------------------------------------

Would anyone be able to tell me what's going on? I'm not even sure where to look.

**Comment by Harmon758** [comment]
[MemoryError](https://docs.python.org/3/library/exceptions.html#MemoryError) is raised when you run out of memory.
This could be occurring because you're storing Status objects in memory or due to something elsewhere in your program and is not an issue with Tweepy.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
