### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by a-atalla** [tweepy/tweepy#951]
i use tweepy in a flask app , today i had this error all the time and never seen it though  it was working before 
Python: 3.6.2
Tweepy: 3.5.0
oauthlib: 2.0.5

```
Traceback (most recent call last):
  File "/home/ahmed/.virtualenvs/Twitips/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ahmed/.virtualenvs/Twitips/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ahmed/.virtualenvs/Twitips/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ahmed/.virtualenvs/Twitips/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ahmed/.virtualenvs/Twitips/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ahmed/.virtualenvs/Twitips/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ahmed/.virtualenvs/Twitips/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ahmed/.virtualenvs/Twitips/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ahmed/.virtualenvs/Twitips/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ahmed/.virtualenvs/Twitips/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ahmed/.virtualenvs/Twitips/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ahmed/Projects/BookTips/Twitips/server/app/auth.py", line 18, in auth_request_token
    url = auth.get_authorization_url()
  File "/home/ahmed/.virtualenvs/Twitips/lib/python3.6/site-packages/tweepy/auth.py", line 91, in get_authorization_url
    raise TweepError(e)
tweepy.error.TweepError: maximum recursion depth exceeded while calling a Python object
```

**Comment by a-atalla** [comment]
I found the solution, all that happened after i install gevent  , when i uninstall it from my venv the code works again

**Comment by SS-FS-58** [comment]
I have faced the same issue, But after I have uninstalled eventlet, it works as well again.
