### ISSUE TITLE
‘Module’ object is not callable

### ISSUE THREAD

**Issue by birchtree02** [tweepy/tweepy#963]
Having this problem with tweepy
`Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/92292B95-D1E2-43B1-BC1C-1324446DF6EB/Pythonista3/Documents/my_scripts/Other/mining demo.py", line 25, in <module>
    auth = OAuthHandler(consumer_key, consumer_secret)
  File "/private/var/mobile/Containers/Shared/AppGroup/92292B95-D1E2-43B1-BC1C-1324446DF6EB/Pythonista3/Documents/site-packages/tweepy/auth.py", line 49, in __init__
    callback_uri=self.callback)
TypeError: 'module' object is not callable`

Line 25 is 
`auth = OAuthHandler(consumer_key, consumer_secret)`

**Comment by fitnr** [comment]
You code snippet works fine for me.

Try running this code:
```python
import requests_oauthlib
requests_oauthlib.OAuth1Session('', '', callback_uri='')
```
You should get a response like `<requests_oauthlib.oauth1_session.OAuth1Session object at 0x103b6add0>`.

If it doesn't work, you have some kind problem with the `requests_oauthlib` library, and should try reinstalling it (`pip install --force-reinstall "requests_oauthlib>=0.7.0"`).
