### ISSUE TITLE
 actual problems / Help !

### ISSUE THREAD

**Issue by Juanca18** [tweepy/tweepy#980]
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python36-32\lib\logging\__init__.py", line 989, in emit
    stream.write(msg)
  File "C:\Program Files\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f525' in position 55: character maps to <undefined>
Call stack:
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python36-32\lib\idlelib\run.py", line 142, in main
    ret = method(*args, **kwargs)
  File "C:\Program Files\Python36-32\lib\idlelib\run.py", line 460, in runcode
    exec(code, self.locals)
  File "D:\LuckyBot-master\LuckyBot-master\src\luckyBot.py", line 290, in <module>
    main()
  File "D:\LuckyBot-master\LuckyBot-master\src\luckyBot.py", line 272, in main
    newContestTweets = getContestTweets()
  File "D:\LuckyBot-master\LuckyBot-master\src\luckyBot.py", line 160, in getContestTweets
    logger.info("Added following tweet to list: " + tweet_text)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.

the bot works but pulls those errors and ends up pausing only

**Comment by braian87b** [comment]
please, edit your post and format it well using code button. or post a github/gist link to the code.

**Comment by Harmon758** [comment]
This is an error with the encoding used by your logger rather than an issue with Tweepy.
Note, the default encoding for [`open`](https://docs.python.org/3/library/functions.html#open) that [`logging.FileHandler`](https://docs.python.org/3/library/logging.handlers.html#logging.FileHandler) and its variants use to open the relevant file is platform dependent.
One of the Tweets you're processing is using characters that the encoding you're using, CP-1252, doesn't support.
This should easily be resolved by using UTF-8 instead.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
