### ISSUE TITLE
there is an error  when i monitor the twitter account?

### ISSUE THREAD

**Issue by kevien** [tweepy/tweepy#982]
Connected to a tweet stream!
Traceback (most recent call last):
  File "twittermonitor.py", line 187, in <module>
    stream.filter(follow=users)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 445, in filter
    self._start(async)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 294, in _run
    raise exception
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by rokn1500** [comment]
this is the same issue as #1003, which i entered 2 days ago. the error occurs in streaming.py, but i do not know how to fix it.

**Comment by rokn1500** [comment]
FANTASTIC.

**Comment by Harmon758** [comment]
This should be fixed by https://github.com/tweepy/tweepy/commit/c1eddf1a5788ec4947d3a363dfe165ea599c31fc and  https://github.com/tweepy/tweepy/commit/32fa592d4ae535baf6e1cf17658d207fb656b16b (#1027) in [3.7.0](https://github.com/tweepy/tweepy/releases/tag/3.7.0).
For more information, see #576, #698, and #1026.
